export const chapterContent3 = {
  'step-six': `
<h2 class="text-xl font-semibold text-white mb-2">Step Six</h2>
<p class="text-teal-400 italic mb-6">"Were entirely ready to have God remove all these defects of character."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>"THIS is the Step that separates the men from the boys." So declares a well-loved clergyman who happens to be one of A.A.'s greatest friends. He goes on to explain that any person capable of enough willingness and honesty to try repeatedly Step Six on all his faults—without any reservations whatever—has indeed come a long way spiritually, and is therefore entitled to be called a man who is sincerely trying to grow in the image and likeness of his own Creator.</p>

<p>Of course, the often disputed question of whether God can—and will, under certain conditions—remove defects of character will be answered with a prompt affirmative by almost any A.A. member. To him, this proposition will be no theory at all; it will be just about the largest fact in his life. He will usually offer his proof in a statement like this:</p>

<p><span class="highlight-result">"Sure, I was beaten, absolutely licked. My own willpower just wouldn't work on alcohol. Change of scene, the best efforts of family, friends, doctors, and clergymen got no place with my alcoholism. I simply couldn't stop drinking, and no human being could seem to do the job for me. But when I became willing to clean house and then asked a Higher Power, God as I understood Him, to give me release, my obsession to drink vanished. It was lifted right out of me."</span></p>

<p>In A.A. meetings all over the world, statements just like this are heard daily. It is plain for everybody to see that each sober A.A. member has been granted a release from this very obstinate and potentially fatal obsession. So in a very complete and literal way, all A.A.'s have "become entirely ready" to have God remove the mania for alcohol from their lives. And God has proceeded to do exactly that.</p>

<p>Having been granted a perfect release from alcoholism, why then shouldn't we be able to achieve by the same means a perfect release from every other difficulty or defect? This is a riddle of our existence, the full answer to which may be only in the mind of God. Nevertheless, at least a part of the answer to it is apparent to us.</p>

<p><span class="highlight-problem">When men and women pour so much alcohol into themselves that they destroy their lives, they commit a most unnatural act. Defying their instinctive desire for self-preservation, they seem bent upon self-destruction.</span> They work against their own deepest instinct. As they are humbled by the terrific beating administered by alcohol, the grace of God can enter them and expel their obsession. Here their powerful instinct to live can cooperate fully with their Creator's desire to give them new life. For nature and God alike abhor suicide.</p>

<p>But most of our other difficulties don't fall under such a category at all. Every normal person wants, for example, to eat, to reproduce, to be somebody in the society of his fellows. And he wishes to be reasonably safe and secure as he tries to attain these things. Indeed, God made him that way. He did not design man to destroy himself by alcohol, but He did give man instincts to help him to stay alive.</p>

<p>It is nowhere evident, at least in this life, that our Creator expects us fully to eliminate our instinctual drives. So far as we know, it is nowhere on the record that God has completely removed from any human being all his natural drives.</p>

<p>Since most of us are born with an abundance of natural desires, it isn't strange that we often let these far exceed their intended purpose. When they drive us blindly, or we willfully demand that they supply us with more satisfactions or pleasures than are possible or due us, that is the point at which we depart from the degree of perfection that God wishes for us here on earth. That is the measure of our character defects, or, if you wish, of our sins.</p>

<p>If we ask, God will certainly forgive our derelictions. But in no case does He render us white as snow and keep us that way without our cooperation. <span class="highlight-action">That is something we are supposed to be willing to work toward ourselves. He asks only that we try as best we know how to make progress in the building of character.</span></p>

<p>So Step Six—"Were entirely ready to have God remove all these defects of character"—is A.A.'s way of stating the best possible attitude one can take in order to make a beginning on this lifetime job. This does not mean that we expect all our character defects to be lifted out of us as the drive to drink was. A few of them may be, but with most of them we shall have to be content with patient improvement. <span class="highlight-action">The key words "entirely ready" underline the fact that we want to aim at the very best we know or can learn.</span></p>

<p>How many of us have this degree of readiness? In an absolute sense practically nobody has it. The best we can do, with all the honesty that we can summon, is to try to have it. Even then the best of us will discover to our dismay that there is always a sticking point, a point at which we say, "No, I can't give this up yet." And we shall often tread on even more dangerous ground when we cry, "This I will never give up!" Such is the power of our instincts to overreach themselves. No matter how far we have progressed, desires will always be found which oppose the grace of God.</p>

<p>Some who feel they have done well may dispute this, so let's try to think it through a little further. Practically everybody wishes to be rid of his most glaring and destructive handicaps. No one wants to be so proud that he is scorned as a braggart, nor so greedy that he is labeled a thief. No one wants to be angry enough to murder, lustful enough to rape, gluttonous enough to ruin his health. No one wants to be agonized by the chronic pain of envy or to be paralyzed by sloth. Of course, most human beings don't suffer these defects at these rock-bottom levels.</p>

<p>We who have escaped these extremes are apt to congratulate ourselves. Yet can we? After all, hasn't it been self-interest, pure and simple, that has enabled most of us to escape? Not much spiritual effort is involved in avoiding excesses which will bring us punishment anyway. But when we face up to the less violent aspects of these very same defects, then where do we stand?</p>

<p><span class="highlight-problem">What we must recognize now is that we exult in some of our defects. We really love them. Who, for example, doesn't like to feel just a little superior to the next fellow, or even quite a lot superior? Isn't it true that we like to let greed masquerade as ambition? To think of liking lust seems impossible. But how many men and women speak love with their lips, and believe what they say, so that they can hide lust in a dark corner of their minds?</span> And even while staying within conventional bounds, many people have to admit that their imaginary sex excursions are apt to be all dressed up as dreams of romance.</p>

<p>Self-righteous anger also can be very enjoyable. In a perverse way we can actually take satisfaction from the fact that many people annoy us, for it brings a comfortable feeling of superiority. Gossip barbed with our anger, a polite form of murder by character assassination, has its satisfactions for us, too. Here we are not trying to help those we criticize; we are trying to proclaim our own righteousness.</p>

<p>When gluttony is less than ruinous, we have a milder word for that, too; we call it "taking our comfort." We live in a world riddled with envy. To a greater or less degree, everybody is infected with it. From this defect we must surely get a warped yet definite satisfaction. Else why would we consume such great amounts of time wishing for what we have not, rather than working for it, or angrily looking for attributes we shall never have, instead of adjusting to the fact, and accepting it? And how often we work hard with no better motive than to be secure and slothful later on—only we call that "retiring." Consider, too, our talents for procrastination, which is really sloth in five syllables. Nearly anyone could submit a good list of such defects as these, and few of us would seriously think of giving them up, at least until they cause us excessive misery.</p>

<p>Some people, of course, may conclude that they are indeed ready to have all such defects taken from them. But even these people, if they construct a list of still milder defects, will be obliged to admit that they prefer to hang on to some of them. Therefore, it seems plain that few of us can quickly or easily become ready to aim at spiritual and moral perfection; we want to settle for only as much perfection as will get us by in life, according, of course, to our various and sundry ideas of what will get us by. <span class="highlight-solution">So the difference between "the boys and the men" is the difference between striving for a self-determined objective and for the perfect objective which is of God.</span></p>

<p>Many will at once ask, "How can we accept the entire implication of Step Six? Why—that is perfection!" This sounds like a hard question, but practically speaking, it isn't. Only Step One, where we made the 100 percent admission we were powerless over alcohol, can be practiced with absolute perfection. <span class="highlight-solution">The remaining eleven Steps state perfect ideals. They are goals toward which we look, and the measuring sticks by which we estimate our progress.</span> Seen in this light, Step Six is still difficult, but not at all impossible. The only urgent thing is that we make a beginning, and keep trying.</p>

<p>If we would gain any real advantage in the use of this Step on problems other than alcohol, we shall need to make a brand new venture into open-mindedness. We shall need to raise our eyes toward perfection, and be ready to walk in that direction. It will seldom matter how haltingly we walk. The only question will be "Are we ready?"</p>

<p>Looking again at those defects we are still unwilling to give up, we ought to erase the hard-and-fast lines that we have drawn. Perhaps we shall be obliged in some cases still to say, "This I cannot give up yet . . . ," but we should not say to ourselves, "This I will never give up!"</p>

<p>Let's dispose of what appears to be a hazardous open end we have left. It is suggested that we ought to become entirely willing to aim toward perfection. We note that some delay, however, might be pardoned. That word, in the mind of a rationalizing alcoholic, could certainly be given a long-term meaning. He could say, "How very easy! Sure, I'll head toward perfection, but I'm certainly not going to hurry any. Maybe I can postpone dealing with some of my problems indefinitely." Of course, this won't do. Such a bluffing of oneself will have to go the way of many another pleasant rationalization. At the very least, we shall have to come to grips with some of our worst character defects and take action toward their removal as quickly as we can.</p>

<p><span class="highlight-action">The moment we say, "No, never!" our minds close against the grace of God. Delay is dangerous, and rebellion may be fatal. This is the exact point at which we abandon limited objectives, and move toward God's will for us.</span></p>
</div>
`,

  'step-seven': `
<h2 class="text-xl font-semibold text-white mb-2">Step Seven</h2>
<p class="text-teal-400 italic mb-6">"Humbly asked Him to remove our shortcomings."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>SINCE this Step so specifically concerns itself with humility, we should pause here to consider what humility is and what the practice of it can mean to us.</p>

<p>Indeed, the attainment of greater humility is the foundation principle of each of A.A.'s Twelve Steps. For without some degree of humility, no alcoholic can stay sober at all. Nearly all A.A.'s have found, too, that unless they develop much more of this precious quality than may be required just for sobriety, they still haven't much chance of becoming truly happy. Without it, they cannot live to much useful purpose, or, in adversity, be able to summon the faith that can meet any emergency.</p>

<p><span class="highlight-problem">Humility, as a word and as an ideal, has a very bad time of it in our world. Not only is the idea misunderstood; the word itself is often intensely disliked. Many people haven't even a nodding acquaintance with humility as a way of life.</span> Much of the everyday talk we hear, and a great deal of what we read, highlights man's pride in his own achievements.</p>

<p>With great intelligence, men of science have been forcing nature to disclose her secrets. The immense resources now being harnessed promise such a quantity of material blessings that many have come to believe that a man-made millennium lies just ahead. Poverty will disappear, and there will be such abundance that everybody can have all the security and personal satisfactions he desires. The theory seems to be that once everybody's primary instincts are satisfied, there won't be much left to quarrel about. The world will then turn happy and be free to concentrate on culture and character. Solely by their own intelligence and labor, men will have shaped their own destiny.</p>

<p>Certainly no alcoholic, and surely no member of A.A., wants to deprecate material achievement. Nor do we enter into debate with the many who still so passionately cling to the belief that to satisfy our basic natural desires is the main object of life. <span class="highlight-problem">But we are sure that no class of people in the world ever made a worse mess of trying to live by this formula than alcoholics. For thousands of years we have been demanding more than our share of security, prestige, and romance. When we seemed to be succeeding, we drank to dream still greater dreams. When we were frustrated, even in part, we drank for oblivion. Never was there enough of what we thought we wanted.</span></p>

<p>In all these strivings, so many of them well-intentioned, our crippling handicap had been our lack of humility. We had lacked the perspective to see that character-building and spiritual values had to come first, and that material satisfactions were not the purpose of living. Quite characteristically, we had gone all out in confusing the ends with the means. Instead of regarding the satisfaction of our material desires as the means by which we could live and function as human beings, we had taken these satisfactions to be the final end and aim of life.</p>

<p>True, most of us thought good character was desirable, but obviously good character was something one needed to get on with the business of being self-satisfied. With a proper display of honesty and morality, we'd stand a better chance of getting what we really wanted. But whenever we had to choose between character and comfort, the character-building was lost in the dust of our chase after what we thought was happiness. Seldom did we look at character-building as something desirable in itself, something we would like to strive for whether our instinctual needs were met or not. We never thought of making honesty, tolerance, and true love of man and God the daily basis of living.</p>

<p><span class="highlight-problem">This lack of anchorage to any permanent values, this blindness to the true purpose of our lives, produced another bad result. For just so long as we were convinced that we could live exclusively by our own individual strength and intelligence, for just that long was a working faith in a Higher Power impossible.</span> This was true even when we believed that God existed. We could actually have earnest religious beliefs which remained barren because we were still trying to play God ourselves. As long as we placed self-reliance first, a genuine reliance upon a Higher Power was out of the question. That basic ingredient of all humility, a desire to seek and do God's will, was missing.</p>

<p><span class="highlight-problem">For us, the process of gaining a new perspective was unbelievably painful. It was only by repeated humiliations that we were forced to learn something about humility. It was only at the end of a long road, marked by successive defeats and humiliations, and the final crushing of our self-sufficiency, that we began to feel humility as something more than a condition of groveling despair.</span> Every newcomer in Alcoholics Anonymous is told, and soon realizes for himself, that his humble admission of powerlessness over alcohol is his first step toward liberation from its paralyzing grip.</p>

<p>So it is that we first see humility as a necessity. But this is the barest beginning. <span class="highlight-solution">To get completely away from our aversion to the idea of being humble, to gain a vision of humility as the avenue to true freedom of the human spirit, to be willing to work for humility as something to be desired for itself, takes most of us a long, long time.</span> A whole lifetime geared to self-centeredness cannot be set in reverse all at once. Rebellion dogs our every step at first.</p>

<p>When we have finally admitted without reservation that we are powerless over alcohol, we are apt to breathe a great sigh of relief, saying, "Well, thank God that's over! I'll never have to go through that again!" Then we learn, often to our consternation, that this is only the first milestone on the new road we are walking. Still goaded by sheer necessity, we reluctantly come to grips with those serious character flaws that made problem drinkers of us in the first place, flaws which must be dealt with to prevent a retreat into alcoholism once again. We will want to be rid of some of these defects, but in some instances this will appear to be an impossible job from which we recoil. And we cling with a passionate persistence to others which are just as disturbing to our equilibrium, because we still enjoy them too much. How can we possibly summon the resolution and the willingness to get rid of such overwhelming compulsions and desires?</p>

<p>But again we are driven on by the inescapable conclusion which we draw from A.A. experience, that we surely must try with a will, or else fall by the wayside. At this stage of our progress we are under heavy pressure and coercion to do the right thing. We are obliged to choose between the pains of trying and the certain penalties of failing to do so. These initial steps along the road are taken grudgingly, yet we do take them. We may still have no very high opinion of humility as a desirable personal virtue, but we do recognize it as a necessary aid to our survival.</p>

<p>But when we have taken a square look at some of these defects, have discussed them with another, and have become willing to have them removed, our thinking about humility commences to have a wider meaning. By this time in all probability we have gained some measure of release from our more devastating handicaps. <span class="highlight-result">We enjoy moments in which there is something like real peace of mind. To those of us who have hitherto known only excitement, depression, or anxiety—in other words, to all of us—this newfound peace is a priceless gift.</span> Something new indeed has been added. Where humility had formerly stood for a forced feeding on humble pie, it now begins to mean the nourishing ingredient which can give us serenity.</p>

<p><span class="highlight-result">This improved perception of humility starts another revolutionary change in our outlook. Our eyes begin to open to the immense values which have come straight out of painful ego-puncturing. Until now, our lives have been largely devoted to running from pain and problems. We fled from them as from a plague. We never wanted to deal with the fact of suffering.</span> Escape via the bottle was always our solution. Character-building through suffering might be all right for saints, but it certainly didn't appeal to us.</p>

<p>Then, in A.A., we looked and listened. Everywhere we saw failure and misery transformed by humility into priceless assets. We heard story after story of how humility had brought strength out of weakness. In every case, pain had been the price of admission into a new life. But this admission price had purchased more than we expected. It brought a measure of humility, which we soon discovered to be a healer of pain. We began to fear pain less, and desire humility more than ever.</p>

<p>During this process of learning more about humility, the most profound result of all was the change in our attitude toward God. And this was true whether we had been believers or unbelievers. We began to get over the idea that the Higher Power was a sort of bush-league pinch hitter, to be called upon only in an emergency. The notion that we would still live our own lives, God helping a little now and then, began to evaporate. Many of us who had thought ourselves religious awoke to the limitations of this attitude. Refusing to place God first, we had deprived ourselves of His help. But now the words "Of myself I am nothing, the Father doeth the works" began to carry bright promise and meaning.</p>

<p>We saw we needn't always be bludgeoned and beaten into humility. It could come quite as much from our voluntary reaching for it as it could from unremitting suffering. <span class="highlight-solution">A great turning point in our lives came when we sought for humility as something we really wanted, rather than as something we must have.</span> It marked the time when we could commence to see the full implication of Step Seven: "Humbly asked Him to remove our shortcomings."</p>

<p>As we approach the actual taking of Step Seven, it might be well if we A.A.'s inquire once more just what our deeper objectives are. Each of us would like to live at peace with himself and with his fellows. We would like to be assured that the grace of God can do for us what we cannot do for ourselves. We have seen that character defects based upon shortsighted or unworthy desires are the obstacles that block our path toward these objectives. We now clearly see that we have been making unreasonable demands upon ourselves, upon others, and upon God.</p>

<p><span class="highlight-problem">The chief activator of our defects has been self-centered fear—primarily fear that we would lose something we already possessed or would fail to get something we demanded. Living upon a basis of unsatisfied demands, we were in a state of continual disturbance and frustration.</span> Therefore, no peace was to be had unless we could find a means of reducing these demands. The difference between a demand and a simple request is plain to anyone.</p>

<p><span class="highlight-action">The Seventh Step is where we make the change in our attitude which permits us, with humility as our guide, to move out from ourselves toward others and toward God. The whole emphasis of Step Seven is on humility. It is really saying to us that we now ought to be willing to try humility in seeking the removal of our other shortcomings just as we did when we admitted that we were powerless over alcohol, and came to believe that a Power greater than ourselves could restore us to sanity.</span> If that degree of humility could enable us to find the grace by which such a deadly obsession could be banished, then there must be hope of the same result respecting any other problem we could possibly have.</p>
</div>
`
};

export default chapterContent3;