export const chapterContent7 = {
  'step-twelve': `
<h2 class="text-xl font-semibold text-white mb-2">Step Twelve</h2>
<p class="text-teal-400 italic mb-6">"Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-result">THE joy of living is the theme of A.A.'s Twelfth Step, and action is its key word.</span> Here we turn outward toward our fellow alcoholics who are still in distress. Here we experience the kind of giving that asks no rewards. Here we begin to practice all Twelve Steps of the program in our daily lives so that we and those about us may find emotional sobriety. When the Twelfth Step is seen in its full implication, it is really talking about the kind of love that has no price tag on it.</p>

<p>Our Twelfth Step also says that as a result of practicing all the Steps, we have each found something called a spiritual awakening. To new A.A.'s, this often seems like a very dubious and improbable state of affairs. "What do you mean when you talk about a 'spiritual awakening'?" they ask.</p>

<p>Maybe there are as many definitions of spiritual awakening as there are people who have had them. But certainly each genuine one has something in common with all the others. And these things which they have in common are not too hard to understand. <span class="highlight-solution">When a man or a woman has a spiritual awakening, the most important meaning of it is that he has now become able to do, feel, and believe that which he could not do before on his unaided strength and resources alone. He has been granted a gift which amounts to a new state of consciousness and being. He has been set on a path which tells him he is really going somewhere, that life is not a dead end, not something to be endured or mastered.</span> In a very real sense he has been transformed, because he has laid hold of a source of strength which, in one way or another, he had hitherto denied himself. He finds himself in possession of a degree of honesty, tolerance, unselfishness, peace of mind, and love of which he had thought himself quite incapable. What he has received is a free gift, and yet usually, at least in some small part, he has made himself ready to receive it.</p>

<p>A.A.'s manner of making ready to receive this gift lies in the practice of the Twelve Steps in our program. So let's consider briefly what we have been trying to do up to this point:</p>

<p>Step One showed us an amazing paradox: We found that we were totally unable to be rid of the alcohol obsession until we first admitted that we were powerless over it. In Step Two we saw that since we could not restore ourselves to sanity, some Higher Power must necessarily do so if we were to survive. Consequently, in Step Three we turned our will and our lives over to the care of God as we understood Him. For the time being, we who were atheist or agnostic discovered that our own group, or A.A. as a whole, would suffice as a higher power. Beginning with Step Four, we commenced to search out the things in ourselves which had brought us to physical, moral, and spiritual bankruptcy. We made a searching and fearless moral inventory. Looking at Step Five, we decided that an inventory, taken alone, wouldn't be enough. We knew we would have to quit the deadly business of living alone with our conflicts, and in honesty confide these to God and another human being. At Step Six, many of us balked—for the practical reason that we did not wish to have all our defects of character removed, because we still loved some of them too much. Yet we knew we had to make a settlement with the fundamental principle of Step Six. So we decided that while we still had some flaws of character that we could not yet relinquish, we ought nevertheless to quit our stubborn, rebellious hanging on to them. We said to ourselves, "This I cannot do today, perhaps, but I can stop crying out 'No, never!'" Then, in Step Seven, we humbly asked God to remove our shortcomings such as He could or would under the conditions of the day we asked. In Step Eight, we continued our housecleaning, for we saw that we were not only in conflict with ourselves, but also with people and situations in the world in which we lived. We had to begin to make our peace, and so we listed the people we had harmed and became willing to set things right. We followed this up in Step Nine by making direct amends to those concerned, except when it would injure them or other people. By this time, at Step Ten, we had begun to get a basis for daily living, and we keenly realized that we would need to continue taking personal inventory, and that when we were in the wrong we ought to admit it promptly. In Step Eleven we saw that if a Higher Power had restored us to sanity and had enabled us to live with some peace of mind in a sorely troubled world, then such a Higher Power was worth knowing better, by as direct contact as possible. The persistent use of meditation and prayer, we found, did open the channel so that where there had been a trickle, there now was a river which led to sure power and safe guidance from God as we were increasingly better able to understand Him.</p>

<p>So, practicing these Steps, we had a spiritual awakening about which finally there was no question. Looking at those who were only beginning and still doubted themselves, the rest of us were able to see the change setting in. From great numbers of such experiences, we could predict that the doubter who still claimed that he hadn't got the "spiritual angle," and who still considered his well-loved A.A. group the higher power, would presently love God and call Him by name.</p>

<p>Now, what about the rest of the Twelfth Step? <span class="highlight-result">The wonderful energy it releases and the eager action by which it carries our message to the next suffering alcoholic and which finally translates the Twelve Steps into action upon all our affairs is the payoff, the magnificent reality, of Alcoholics Anonymous.</span></p>

<p><span class="highlight-action">Even the newest of newcomers finds undreamed rewards as he tries to help his brother alcoholic, the one who is even blinder than he. This is indeed the kind of giving that actually demands nothing.</span> He does not expect his brother sufferer to pay him, or even to love him. And then he discovers that by the divine paradox of this kind of giving he has found his own reward, whether his brother has yet received anything or not. His own character may still be gravely defective, but he somehow knows that God has enabled him to make a mighty beginning, and he senses that he stands at the edge of new mysteries, joys, and experiences of which he had never even dreamed.</p>

<p><span class="highlight-result">Practically every A.A. member declares that no satisfaction has been deeper and no joy greater than in a Twelfth Step job well done. To watch the eyes of men and women open with wonder as they move from darkness into light, to see their lives quickly fill with new purpose and meaning, to see whole families reassembled, to see the alcoholic outcast received back into his community in full citizenship, and above all to watch these people awaken to the presence of a loving God in their lives—these things are the substance of what we receive as we carry A.A.'s message to the next alcoholic.</span></p>

<p>Nor is this the only kind of Twelfth Step work. We sit in A.A. meetings and listen, not only to receive something ourselves, but to give the reassurance and support which our presence can bring. If our turn comes to speak at a meeting, we again try to carry A.A.'s message. Whether our audience is one or many, it is still Twelfth Step work. There are many opportunities even for those of us who feel unable to speak at meetings or who are so situated that we cannot do much face-to-face Twelfth Step work. We can be the ones who take on the unspectacular but important tasks that make good Twelfth Step work possible, perhaps arranging for the coffee and cake after the meetings, where so many skeptical, suspicious newcomers have found confidence and comfort in the laughter and talk. This is Twelfth Step work in the very best sense of the word. "Freely ye have received; freely give . . ." is the core of this part of Step Twelve.</p>

<p>We may often pass through Twelfth Step experiences where we will seem to be temporarily off the beam. These will appear as big setbacks at the time, but will be seen later as stepping-stones to better things. For example, we may set our hearts on getting a particular person sobered up, and after doing all we can for months, we see him relapse. Perhaps this will happen in a succession of cases, and we may be deeply discouraged as to our ability to carry A.A.'s message. Or we may encounter the reverse situation, in which we are highly elated because we seem to have been successful. Here the temptation is to become rather possessive of these newcomers. Perhaps we try to give them advice about their affairs which we aren't really competent to give or ought not give at all. Then we are hurt and confused when the advice is rejected, or when it is accepted and brings still greater confusion. By a great deal of ardent Twelfth Step work we sometimes carry the message to so many alcoholics that they place us in a position of trust. They make us, let us say, the group's chairman. Here again we are presented with the temptation to overmanage things, and sometimes this results in rebuffs and other consequences which are hard to take.</p>

<p>But in the longer run we clearly realize that these are only the pains of growing up, and nothing but good can come from them if we turn more and more to the entire Twelve Steps for the answers.</p>

<p>Now comes the biggest question yet. What about the practice of these principles in all our affairs? Can we love the whole pattern of living as eagerly as we do the small segment of it we discover when we try to help other alcoholics achieve sobriety? Can we bring the same spirit of love and tolerance into our sometimes deranged family lives that we bring to our A.A. group? Can we have the same kind of confidence and faith in these people who have been infected and sometimes crippled by our own illness that we have in our sponsors? Can we actually carry the A.A. spirit into our daily work? Can we meet our newly recognized responsibilities to the world at large? And can we bring new purpose and devotion to the religion of our choice? Can we find a new joy of living in trying to do something about all these things?</p>

<p>Furthermore, how shall we come to terms with seeming failure or success? Can we now accept and adjust to either without despair or pride? Can we accept poverty, sickness, loneliness, and bereavement with courage and serenity? Can we steadfastly content ourselves with the humbler, yet sometimes more durable, satisfactions when the brighter, more glittering achievements are denied us?</p>

<p><span class="highlight-solution">The A.A. answer to these questions about living is "Yes, all of these things are possible." We know this because we see monotony, pain, and even calamity turned to good use by those who keep on trying to practice A.A.'s Twelve Steps.</span> And if these are facts of life for the many alcoholics who have recovered in A.A., they can become the facts of life for many more.</p>

<p>Of course all A.A.'s, even the best, fall far short of such achievements as a consistent thing. Without necessarily taking that first drink, we often get quite far off the beam. Our troubles sometimes begin with indifference. We are sober and happy in our A.A. work. Things go well at home and office. We naturally congratulate ourselves on what later proves to be a far too easy and superficial point of view. We temporarily cease to grow because we feel satisfied that there is no need for all of A.A.'s Twelve Steps for us. We are doing fine on a few of them. Maybe we are doing fine on only two of them, the First Step and that part of the Twelfth where we "carry the message." <span class="highlight-problem">In A.A. slang, that blissful state is known as "two-stepping." And it can go on for years.</span></p>

<p>The best-intentioned of us can fall for the "two-step" illusion. Sooner or later the pink cloud stage wears off and things go disappointingly dull. We begin to think that A.A. doesn't pay off after all. We become puzzled and discouraged.</p>

<p>Then perhaps life, as it has a way of doing, suddenly hands us a great big lump that we can't begin to swallow, let alone digest. We fail to get a worked-for promotion. We lose that good job. Maybe there are serious domestic or romantic difficulties, or perhaps that boy we thought God was looking after becomes a military casualty.</p>

<p>What then? Have we alcoholics in A.A. got, or can we get, the resources to meet these calamities which come to so many? These were problems of life which we could never face up to. Can we now, with the help of God as we understand Him, handle them as well and as bravely as our nonalcoholic friends often do? Can we transform these calamities into assets, sources of growth and comfort to ourselves and those about us? <span class="highlight-action">Well, we surely have a chance if we switch from "two-stepping" to "twelve-stepping," if we are willing to receive that grace of God which can sustain and strengthen us in any catastrophe.</span></p>

<p>Our basic troubles are the same as everyone else's, but when an honest effort is made "to practice these principles in all our affairs," well-grounded A.A.'s seem to have the ability, by God's grace, to take these troubles in stride and turn them into demonstrations of faith. We have seen A.A.'s suffer lingering and fatal illness with little complaint, and often in good cheer. We have sometimes seen families broken apart by misunderstanding, tensions, or actual infidelity, who are reunited by the A.A. way of life.</p>

<p>Though the earning power of most A.A.'s is relatively high, we have some members who never seem to get on their feet moneywise, and still others who encounter heavy financial reverses. Ordinarily we see these situations met with fortitude and faith.</p>

<p>Like most people, we have found that we can take our big lumps as they come. But also like others, we often discover a greater challenge in the lesser and more continuous problems of life. <span class="highlight-solution">Our answer is in still more spiritual development. Only by this means can we improve our chances for really happy and useful living. And as we grow spiritually, we find that our old attitudes toward our instincts need to undergo drastic revisions.</span> Our desires for emotional security and wealth, for personal prestige and power, for romance, and for family satisfactions—all these have to be tempered and redirected. We have learned that the satisfaction of instincts cannot be the sole end and aim of our lives. If we place instincts first, we have got the cart before the horse; we shall be pulled backward into disillusionment. But when we are willing to place spiritual growth first—then and only then do we have a real chance.</p>

<p>After we come into A.A., if we go on growing, our attitudes and actions toward security—emotional security and financial security—commence to change profoundly. Our demand for emotional security, for our own way, had constantly thrown us into unworkable relations with other people. Though we were sometimes quite unconscious of this, the result always had been the same. Either we had tried to play God and dominate those about us, or we had insisted on being overdependent upon them. Where people had temporarily let us run their lives as though they were still children, we had felt very happy and secure ourselves. But when they finally resisted or ran away, we were bitterly hurt and disappointed. We blamed them, being quite unable to see that our unreasonable demands had been the cause.</p>

<p>When we had taken the opposite tack and had insisted, like infants ourselves, that people protect and take care of us or that the world owed us a living, then the result had been equally unfortunate. This often caused the people we had loved most to push us aside or perhaps desert us entirely. Our disillusionment had been hard to bear. We couldn't imagine people acting that way toward us. We had failed to see that though adult in years we were still behaving childishly, trying to turn everybody—friends, wives, husbands, even the world itself—into protective parents. We had refused to learn the very hard lesson that overdependence upon people is unsuccessful because all people are fallible, and even the best of them will sometimes let us down, especially when our demands for attention become unreasonable.</p>

<p>As we made spiritual progress, we saw through these fallacies. It became clear that if we ever were to feel emotionally secure among grown-up people, we would have to put our lives on a give-and-take basis; we would have to develop the sense of being in partnership or brotherhood with all those around us. We saw that we would need to give constantly of ourselves without demands for repayment. When we persistently did this we gradually found that people were attracted to us as never before. And even if they failed us, we could be understanding and not too seriously affected.</p>

<p><span class="highlight-solution">When we developed still more, we discovered the best possible source of emotional stability to be God Himself. We found that dependence upon His perfect justice, forgiveness, and love was healthy, and that it would work where nothing else would. If we really depended upon God, we couldn't very well play God to our fellows nor would we feel the urge wholly to rely on human protection and care.</span> These were the new attitudes that finally brought many of us an inner strength and peace that could not be deeply shaken by the shortcomings of others or by any calamity not of our own making.</p>

<p>This new outlook was, we learned, something especially necessary to us alcoholics. For alcoholism had been a lonely business, even though we had been surrounded by people who loved us. But when self-will had driven everybody away and our isolation had become complete, it caused us to play the big shot in cheap barrooms and then fare forth alone on the street to depend upon the charity of passersby. We were still trying to find emotional security by being dominating or dependent upon others. Even when our fortunes had not ebbed that much and we nevertheless found ourselves alone in the world, we still vainly tried to be secure by some unhealthy kind of domination or dependence. For those of us who were like that, A.A. had a very special meaning. Through it we begin to learn right relations with people who understand us; we don't have to be alone anymore.</p>

<p class="bg-slate-700/30 p-6 rounded-lg mt-8 text-center">
<span class="text-slate-300 italic">God grant us the serenity to accept the things we cannot change,<br/>
Courage to change the things we can,<br/>
And wisdom to know the difference.</span>
</p>
</div>
`
};

export default chapterContent7;