export const chapterContent4 = {
  'step-eight': `
<h2 class="text-xl font-semibold text-white mb-2">Step Eight</h2>
<p class="text-teal-400 italic mb-6">"Made a list of all persons we had harmed, and became willing to make amends to them all."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>STEPS Eight and Nine are concerned with personal relations. First, we take a look backward and try to discover where we have been at fault; next we make a vigorous attempt to repair the damage we have done; and third, having thus cleaned away the debris of the past, we consider how, with our newfound knowledge of ourselves, we may develop the best possible relations with every human being we know.</p>

<p>This is a very large order. It is a task which we may perform with increasing skill, but never really finish. <span class="highlight-action">Learning how to live in the greatest peace, partnership, and brotherhood with all men and women, of whatever description, is a moving and fascinating adventure.</span> Every A.A. has found that he can make little headway in this new adventure of living until he first backtracks and really makes an accurate and unsparing survey of the human wreckage he has left in his wake. To a degree, he has already done this when taking moral inventory, but now the time has come when he ought to redouble his efforts to see how many people he has hurt, and in what ways. This reopening of emotional wounds, some old, some perhaps forgotten, and some still painfully festering, will at first look like a purposeless and pointless piece of surgery. But if a willing start is made, then the great advantages of doing this will so quickly reveal themselves that the pain will be lessened as one obstacle after another melts away.</p>

<p><span class="highlight-problem">These obstacles, however, are very real. The first, and one of the most difficult, has to do with forgiveness. The moment we ponder a twisted or broken relationship with another person, our emotions go on the defensive. To escape looking at the wrongs we have done another, we resentfully focus on the wrong he has done us.</span> This is especially true if he has, in fact, behaved badly at all. Triumphantly we seize upon his misbehavior as the perfect excuse for minimizing or forgetting our own.</p>

<p>Right here we need to fetch ourselves up sharply. It doesn't make much sense when a real toss pot calls a kettle black. Let's remember that alcoholics are not the only ones bedeviled by sick emotions. Moreover, it is usually a fact that our behavior when drinking has aggravated the defects of others. We've repeatedly strained the patience of our best friends to a snapping point, and have brought out the very worst in those who didn't think much of us to begin with. In many instances we are really dealing with fellow sufferers, people whose woes we have increased. <span class="highlight-action">If we are now about to ask forgiveness for ourselves, why shouldn't we start out by forgiving them, one and all?</span></p>

<p>When listing the people we have harmed, most of us hit another solid obstacle. We got a pretty severe shock when we realized that we were preparing to make a face-to-face admission of our wretched conduct to those we had hurt. It had been embarrassing enough when in confidence we had admitted these things to God, to ourselves, and to another human being. But the prospect of actually visiting or even writing the people concerned now overwhelmed us, especially when we remembered in what poor favor we stood with most of them. There were cases, too, where we had damaged others who were still happily unaware of being hurt. Why, we cried, shouldn't bygones be bygones? Why do we have to think of these people at all? These were some of the ways in which fear conspired with pride to hinder our making a list of all the people we had harmed.</p>

<p>Some of us, though, tripped over a very different snag. We clung to the claim that when drinking we never hurt anybody but ourselves. Our families didn't suffer, because we always paid the bills and seldom drank at home. Our business associates didn't suffer, because we were usually on the job. Our reputations hadn't suffered, because we were certain few knew of our drinking. Those who did would sometimes assure us that, after all, a lively bender was only a good man's fault. What real harm, therefore, had we done? No more, surely, than we could easily mend with a few casual apologies.</p>

<p>This attitude, of course, is the end result of purposeful forgetting. It is an attitude which can only be changed by a deep and honest search of our motives and actions.</p>

<p>Though in some cases we cannot make restitution at all, and in some cases action ought to be deferred, we should nevertheless make an accurate and really exhaustive survey of our past life as it has affected other people. <span class="highlight-action">In many instances we shall find that though the harm done others has not been great, the emotional harm we have done ourselves has.</span> Very deep, sometimes quite forgotten, damaging emotional conflicts persist below the level of consciousness. At the time of these occurrences, they may actually have given our emotions violent twists which have since discolored our personalities and altered our lives for the worse.</p>

<p>While the purpose of making restitution to others is paramount, it is equally necessary that we extricate from an examination of our personal relations every bit of information about ourselves and our fundamental difficulties that we can. Since defective relations with other human beings have nearly always been the immediate cause of our woes, including our alcoholism, no field of investigation could yield more satisfying and valuable rewards than this one. Calm, thoughtful reflection upon personal relations can deepen our insight. We can go far beyond those things which were superficially wrong with us, to see those flaws which were basic, flaws which sometimes were responsible for the whole pattern of our lives. <span class="highlight-result">Thoroughness, we have found, will pay—and pay handsomely.</span></p>

<p>We might next ask ourselves what we mean when we say that we have "harmed" other people. What kinds of "harm" do people do one another, anyway? To define the word "harm" in a practical way, we might call it the result of instincts in collision, which cause physical, mental, emotional, or spiritual damage to people. If our tempers are consistently bad, we arouse anger in others. If we lie or cheat, we deprive others not only of their worldly goods, but of their emotional security and peace of mind. We really issue them an invitation to become contemptuous and vengeful. If our sex conduct is selfish, we may excite jealousy, misery, and a strong desire to retaliate in kind.</p>

<p>Such gross misbehavior is not by any means a full catalogue of the harms we do. Let us think of some of the subtler ones which can sometimes be quite as damaging. Suppose that in our family lives we happen to be miserly, irresponsible, callous, or cold. Suppose we are irritable, critical, impatient, and humorless. Suppose we lavish attention upon one member of the family and neglect the others. What happens when we try to dominate the whole family, either by a rule of iron or by a constant outpouring of minute directions for just how their lives should be lived from hour to hour? What happens when we wallow in depression, self-pity oozing from every pore, and inflict that upon those about us? Such a roster of harms done others—the kind that make daily living with us as practicing alcoholics difficult and often unbearable could be extended almost indefinitely. When we take such personality traits as these into shop, office, and the society of our fellows, they can do damage almost as extensive as that we have caused at home.</p>

<p>Having carefully surveyed this whole area of human relations, and having decided exactly what personality traits in us injured and disturbed others, we can now commence to ransack memory for the people to whom we have given offense. To put a finger on the nearby and most deeply damaged ones shouldn't be hard to do. Then, as year by year we walk back through our lives as far as memory will reach, we shall be bound to construct a long list of people who have, to some extent or other, been affected. We should, of course, ponder and weigh each instance carefully. <span class="highlight-action">We shall want to hold ourselves to the course of admitting the things we have done, meanwhile forgiving the wrongs done us, real or fancied. We should avoid extreme judgments, both of ourselves and of others involved. We must not exaggerate our defects or theirs.</span> A quiet, objective view will be our steadfast aim.</p>

<p><span class="highlight-result">Whenever our pencil falters, we can fortify and cheer ourselves by remembering what A.A. experience in this Step has meant to others. It is the beginning of the end of isolation from our fellows and from God.</span></p>
</div>
`,

  'step-nine': `
<h2 class="text-xl font-semibold text-white mb-2">Step Nine</h2>
<p class="text-teal-400 italic mb-6">"Made direct amends to such people wherever possible, except when to do so would injure them or others."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-action">GOOD judgment, a careful sense of timing, courage, and prudence—these are the qualities we shall need when we take Step Nine.</span></p>

<p>After we have made the list of people we have harmed, have reflected carefully upon each instance, and have tried to possess ourselves of the right attitude in which to proceed, we will see that the making of direct amends divides those we should approach into several classes. There will be those who ought to be dealt with just as soon as we become reasonably confident that we can maintain our sobriety. There will be those to whom we can make only partial restitution, lest complete disclosures do them or others more harm than good. There will be other cases where action ought to be deferred, and still others in which by the very nature of the situation we shall never be able to make direct personal contact at all.</p>

<p>Most of us begin making certain kinds of direct amends from the day we join Alcoholics Anonymous. The moment we tell our families that we are really going to try the program, the process has begun. In this area there are seldom any questions of timing or caution. We want to come in the door shouting the good news. After coming from our first meeting, or perhaps after we have finished reading the book "Alcoholics Anonymous," we usually want to sit down with some member of the family and readily admit the damage we have done by our drinking. Almost always we want to go further and admit other defects that have made us hard to live with. This will be a very different occasion, and in sharp contrast with those hangover mornings when we alternated between reviling ourselves and blaming the family (and everyone else) for our troubles. At this first sitting, it is necessary only that we make a general admission of our defects. <span class="highlight-solution">It may be unwise at this stage to rehash certain harrowing episodes. Good judgment will suggest that we ought to take our time. While we may be quite willing to reveal the very worst, we must be sure to remember that we cannot buy our own peace of mind at the expense of others.</span></p>

<p>Much the same approach will apply at the office or factory. We shall at once think of a few people who know all about our drinking, and who have been most affected by it. But even in these cases, we may need to use a little more discretion than we did with the family. We may not want to say anything for several weeks, or longer. First we will wish to be reasonably certain that we are on the A.A. beam. Then we are ready to go to these people, to tell them what A.A. is, and what we are trying to do. Against this background we can freely admit the damage we have done and make our apologies. We can pay, or promise to pay, whatever obligations, financial or otherwise, we owe. <span class="highlight-result">The generous response of most people to such quiet sincerity will often astonish us. Even our severest and most justified critics will frequently meet us more than halfway on the first trial.</span></p>

<p>This atmosphere of approval and praise is apt to be so exhilarating as to put us off balance by creating an insatiable appetite for more of the same. Or we may be tipped over in the other direction when, in rare cases, we get a cool and skeptical reception. This will tempt us to argue, or to press our point insistently. Or maybe it will tempt us to discouragement and pessimism. But if we have prepared ourselves well in advance, such reactions will not deflect us from our steady and even purpose.</p>

<p>After taking this preliminary trial at making amends, we may enjoy such a sense of relief that we conclude our task is finished. We will want to rest on our laurels. The temptation to skip the more humiliating and dreaded meetings that still remain may be great. We will often manufacture plausible excuses for dodging these issues entirely. Or we may just procrastinate, telling ourselves the time is not yet, when in reality we have already passed up many a fine chance to right a serious wrong. <span class="highlight-action">Let's not talk prudence while practicing evasion.</span></p>

<p>As soon as we begin to feel confident in our new way of life and have begun, by our behavior and example, to convince those about us that we are indeed changing for the better, it is usually safe to talk in complete frankness with those who have been seriously affected, even those who may be only a little or not at all aware of what we have done to them. The only exceptions we will make will be cases where our disclosure would cause actual harm. These conversations can begin in a casual or natural way. But if no such opportunity presents itself, at some point we will want to summon all our courage, head straight for the person concerned, and lay our cards on the table. We needn't wallow in excessive remorse before those we have harmed, but amends at this level should always be forthright and generous.</p>

<p><span class="highlight-solution">There can only be one consideration which should qualify our desire for a complete disclosure of the damage we have done. That will arise in the occasional situation where to make a full revelation would seriously harm the one to whom we are making amends. Or—quite as important—other people.</span> We cannot, for example, unload a detailed account of extramarital adventuring upon the shoulders of our unsuspecting wife or husband. And even in those cases where such a matter must be discussed, let's try to avoid harming third parties, whoever they may be. It does not lighten our burden when we recklessly make the crosses of others heavier.</p>

<p>Many a razor-edged question can arise in other departments of life where this same principle is involved. Suppose, for instance, that we have drunk up a good chunk of our firm's money, whether by "borrowing" or on a heavily padded expense account. Suppose that this may continue to go undetected, if we say nothing. Do we instantly confess our irregularities to the firm, in the practical certainty that we will be fired and become unemployable? Are we going to be so rigidly righteous about making amends that we don't care what happens to the family and home? Or do we first consult those who are to be gravely affected? Do we lay the matter before our sponsor or spiritual adviser, earnestly asking God's help and guidance—meanwhile resolving to do the right thing when it becomes clear, cost what it may? Of course, there is no pat answer which can fit all such dilemmas. But all of them do require a complete willingness to make amends as fast and as far as may be possible in a given set of conditions.</p>

<p><span class="highlight-action">Above all, we should try to be absolutely sure that we are not delaying because we are afraid. For the readiness to take the full consequences of our past acts, and to take responsibility for the well-being of others at the same time, is the very spirit of Step Nine.</span></p>
</div>
`
};

export default chapterContent4;