export const chapterContent2 = {
  'step-four': `
<h2 class="text-xl font-semibold text-white mb-2">Step Four</h2>
<p class="text-teal-400 italic mb-6">"Made a searching and fearless moral inventory of ourselves."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>CREATION gave us instincts for a purpose. Without them we wouldn't be complete human beings. If men and women didn't exert themselves to be secure in their persons, made no effort to harvest food or construct shelter, there would be no survival. If they didn't reproduce, the earth wouldn't be populated. If there were no social instinct, if men cared nothing for the society of one another, there would be no society. So these desires—for the sex relation, for material and emotional security, and for companionship—are perfectly necessary and right, and surely God-given.</p>

<p><span class="highlight-problem">Yet these instincts, so necessary for our existence, often far exceed their proper functions. Powerfully, blindly, many times subtly, they drive us, dominate us, and insist upon ruling our lives. Our desires for sex, for material and emotional security, and for an important place in society often tyrannize us.</span> When thus out of joint, man's natural desires cause him great trouble, practically all the trouble there is. No human being, however good, is exempt from these troubles. Nearly every serious emotional problem can be seen as a case of misdirected instinct. When that happens, our great natural assets, the instincts, have turned into physical and mental liabilities.</p>

<p><span class="highlight-action">Step Four is our vigorous and painstaking effort to discover what these liabilities in each of us have been, and are.</span> We want to find exactly how, when, and where our natural desires have warped us. We wish to look squarely at the unhappiness this has caused others and ourselves. By discovering what our emotional deformities are, we can move toward their correction. Without a willing and persistent effort to do this, there can be little sobriety or contentment for us. Without a searching and fearless moral inventory, most of us have found that the faith which really works in daily living is still out of reach.</p>

<p>Before tackling the inventory problem in detail, let's have a closer look at what the basic problem is. Simple examples like the following take on a world of meaning when we think about them. Suppose a person places sex desire ahead of everything else. In such a case, this imperious urge can destroy his chances for material and emotional security as well as his standing in the community. Another may develop such an obsession for financial security that he wants to do nothing but hoard money. Going to the extreme, he can become a miser, or even a recluse who denies himself both family and friends.</p>

<p>Nor is the quest for security always expressed in terms of money. How frequently we see a frightened human being determined to depend completely upon a stronger person for guidance and protection. This weak one, failing to meet life's responsibilities with his own resources, never grows up. Disillusionment and helplessness are his lot. In time all his protectors either flee or die, and he is once more left alone and afraid.</p>

<p>We have also seen men and women who go power-mad, who devote themselves to attempting to rule their fellows. These people often throw to the winds every chance for legitimate security and a happy family life. Whenever a human being becomes a battleground for the instincts, there can be no peace.</p>

<p>But that is not all of the danger. Every time a person imposes his instincts unreasonably upon others, unhappiness follows. If the pursuit of wealth tramples upon people who happen to be in the way, then anger, jealousy, and revenge are likely to be aroused. If sex runs riot, there is a similar uproar. Demands made upon other people for too much attention, protection, and love can only invite domination or revulsion in the protectors themselves—two emotions quite as unhealthy as the demands which evoked them. When an individual's desire for prestige becomes uncontrollable, whether in the sewing circle or at the international conference table, other people suffer and often revolt. This collision of instincts can produce anything from a cold snub to a blazing revolution. In these ways we are set in conflict not only with ourselves, but with other people who have instincts, too.</p>

<p><span class="highlight-problem">Alcoholics especially should be able to see that instinct run wild in themselves is the underlying cause of their destructive drinking. We have drunk to drown feelings of fear, frustration, and depression. We have drunk to escape the guilt of passions, and then have drunk again to make more passions possible. We have drunk for vainglory—that we might the more enjoy foolish dreams of pomp and power.</span> This perverse soul-sickness is not pleasant to look upon. Instincts on rampage balk at investigation. The minute we make a serious attempt to probe them, we are liable to suffer severe reactions.</p>

<p>If temperamentally we are on the depressive side, we are apt to be swamped with guilt and self-loathing. We wallow in this messy bog, often getting a misshapen and painful pleasure out of it. As we morbidly pursue this melancholy activity, we may sink to such a point of despair that nothing but oblivion looks possible as a solution. Here, of course, we have lost all perspective, and therefore all genuine humility. For this is pride in reverse. This is not a moral inventory at all; it is the very process by which the depressive has so often been led to the bottle and extinction.</p>

<p>If, however, our natural disposition is inclined to self-righteousness or grandiosity, our reaction will be just the opposite. We will be offended at A.A.'s suggested inventory. No doubt we shall point with pride to the good lives we thought we led before the bottle cut us down. We shall claim that our serious character defects, if we think we have any at all, have been caused chiefly by excessive drinking. This being so, we think it logically follows that sobriety—first, last, and all the time—is the only thing we need to work for. We believe that our one-time good characters will be revived the moment we quit alcohol. If we were pretty nice people all along, except for our drinking, what need is there for a moral inventory now that we are sober?</p>

<p>We also clutch at another wonderful excuse for avoiding an inventory. Our present anxieties and troubles, we cry, are caused by the behavior of other people—people who really need a moral inventory. We firmly believe that if only they'd treat us better, we'd be all right. Therefore we think our indignation is justified and reasonable—that our resentments are the "right kind." We aren't the guilty ones. They are!</p>

<p>At this stage of the inventory proceedings, our sponsors come to the rescue. They can do this, for they are the carriers of A.A.'s tested experience with Step Four. <span class="highlight-solution">They comfort the melancholy one by first showing him that his case is not strange or different, that his character defects are probably not more numerous or worse than those of anyone else in A.A. This the sponsor promptly proves by talking freely and easily, and without exhibitionism, about his own defects, past and present.</span> This calm, yet realistic, stock-taking is immensely reassuring. The sponsor probably points out that the newcomer has some assets which can be noted along with his liabilities. This tends to clear away morbidity and encourage balance. As soon as he begins to be more objective, the newcomer can fearlessly, rather than fearfully, look at his own defects.</p>

<p>The sponsors of those who feel they need no inventory are confronted with quite another problem. This is because people who are driven by pride of self unconsciously blind themselves to their liabilities. These newcomers scarcely need comforting. The problem is to help them discover a chink in the walls their ego has built, through which the light of reason can shine.</p>

<p>First off, they can be told that the majority of A.A. members have suffered severely from self-justification during their drinking days. For most of us, self-justification was the maker of excuses; excuses, of course, for drinking, and for all kinds of crazy and damaging conduct. We had made the invention of alibis a fine art. We had to drink because times were hard or times were good. We had to drink because at home we were smothered with love or got none at all. We had to drink because at work we were great successes or dismal failures. We had to drink because our nation had won a war or lost a peace. And so it went, ad infinitum.</p>

<p><span class="highlight-problem">We thought "conditions" drove us to drink, and when we tried to correct these conditions and found that we couldn't to our entire satisfaction, our drinking went out of hand and we became alcoholics. It never occurred to us that we needed to change ourselves to meet conditions, whatever they were.</span></p>

<p><span class="highlight-action">But in A.A. we slowly learned that something had to be done about our vengeful resentments, self-pity, and unwarranted pride. We had to see that every time we played the big shot, we turned people against us. We had to see that when we harbored grudges and planned revenge for such defeats, we were really beating ourselves with the club of anger we had intended to use on others.</span> We learned that if we were seriously disturbed, our first need was to quiet that disturbance, regardless of who or what we thought caused it.</p>

<p>To see how erratic emotions victimized us often took a long time. We could perceive them quickly in others, but only slowly in ourselves. First of all, we had to admit that we had many of these defects, even though such disclosures were painful and humiliating. Where other people were concerned, we had to drop the word "blame" from our speech and thought. This required great willingness even to begin. But once over the first two or three high hurdles, the course ahead began to look easier. <span class="highlight-result">For we had started to get perspective on ourselves, which is another way of saying that we were gaining in humility.</span></p>

<p>Of course the depressive and the power-driver are personality extremes, types with which A.A. and the whole world abound. Often these personalities are just as sharply defined as the examples given. But just as often some of us will fit more or less into both classifications. Human beings are never quite alike, so each of us, when making an inventory, will need to determine what his individual character defects are. Having found the shoes that fit, he ought to step into them and walk with new confidence that he is at last on the right track.</p>

<p>Now let's ponder the need for a list of the more glaring personality defects all of us have in varying degrees. To those having religious training, such a list would set forth serious violations of moral principles. Some others will think of this list as defects of character. Still others will call it an index of maladjustments. Some will become quite annoyed if there is talk about immorality, let alone sin. But all who are in the least reasonable will agree upon one point: that there is plenty wrong with us alcoholics about which plenty will have to be done if we are to expect sobriety, progress, and any real ability to cope with life.</p>

<p>To avoid falling into confusion over the names these defects should be called, let's take a universally recognized list of major human failings—the Seven Deadly Sins of pride, greed, lust, anger, gluttony, envy, and sloth. <span class="highlight-problem">It is not by accident that pride heads the procession. For pride, leading to self-justification, and always spurred by conscious or unconscious fears, is the basic breeder of most human difficulties, the chief block to true progress. Pride lures us into making demands upon ourselves or upon others which cannot be met without perverting or misusing our God-given instincts.</span> When the satisfaction of our instincts for sex, security, and society becomes the sole object of our lives, then pride steps in to justify our excesses.</p>

<p>All these failings generate fear, a soul-sickness in its own right. Then fear, in turn, generates more character defects. Unreasonable fear that our instincts will not be satisfied drives us to covet the possessions of others, to lust for sex and power, to become angry when our instinctive demands are threatened, to be envious when the ambitions of others seem to be realized while ours are not. We eat, drink, and grab for more of everything than we need, fearing we shall never have enough. And with genuine alarm at the prospect of work, we stay lazy. We loaf and procrastinate, or at best work grudgingly and under half steam. These fears are the termites that ceaselessly devour the foundations of whatever sort of life we try to build.</p>

<p>So when A.A. suggests a fearless moral inventory, it must seem to every newcomer that more is being asked of him than he can do. Both his pride and his fear beat him back every time he tries to look within himself. Pride says, "You need not pass this way," and Fear says, "You dare not look!" <span class="highlight-result">But the testimony of A.A.'s who have really tried a moral inventory is that pride and fear of this sort turn out to be bogeymen, nothing else. Once we have a complete willingness to take inventory, and exert ourselves to do the job thoroughly, a wonderful light falls upon this foggy scene. As we persist, a brand-new kind of confidence is born, and the sense of relief at finally facing ourselves is indescribable. These are the first fruits of Step Four.</span></p>

<p>By now the newcomer has probably arrived at the following conclusions: that his character defects, representing instincts gone astray, have been the primary cause of his drinking and his failure at life; that unless he is now willing to work hard at the elimination of the worst of these defects, both sobriety and peace of mind will still elude him; that all the faulty foundation of his life will have to be torn out and built anew on bedrock. Now willing to commence the search for his own defects, he will ask, "Just how do I go about this? How do I take inventory of myself?"</p>

<p><span class="highlight-action">Since Step Four is but the beginning of a lifetime practice, it can be suggested that he first have a look at those personal flaws which are acutely troublesome and fairly obvious.</span> Using his best judgment of what has been right and what has been wrong, he might make a rough survey of his conduct with respect to his primary instincts for sex, security, and society. Looking back over his life, he can readily get under way by consideration of questions such as these:</p>

<p>When, and how, and in just what instances did my selfish pursuit of the sex relation damage other people and me? What people were hurt, and how badly? Did I spoil my marriage and injure my children? Did I jeopardize my standing in the community? Just how did I react to these situations at the time? Did I burn with a guilt that nothing could extinguish? Or did I insist that I was the pursued and not the pursuer, and thus absolve myself? How have I reacted to frustration in sexual matters? When denied, did I become vengeful or depressed? Did I take it out on other people? If there was rejection or coldness at home, did I use this as a reason for promiscuity?</p>

<p>Also of importance for most alcoholics are the questions they must ask about their behavior respecting financial and emotional security. In these areas fear, greed, possessiveness, and pride have too often done their worst. Surveying his business or employment record, almost any alcoholic can ask questions like these: In addition to my drinking problem, what character defects contributed to my financial instability? Did fear and inferiority about my fitness for my job destroy my confidence and fill me with conflict? Did I try to cover up those feelings of inadequacy by bluffing, cheating, lying, or evading responsibility? Or by griping that others failed to recognize my truly exceptional abilities? Did I overvalue myself and play the big shot? Did I have such unprincipled ambition that I double-crossed and undercut my associates? Was I extravagant? Did I recklessly borrow money, caring little whether it was repaid or not? Was I a pinch penny, refusing to support my family properly? Did I cut corners financially? What about the "quick money" deals, the stock market, and the races?</p>

<p>Businesswomen in A.A. will naturally find that many of these questions apply to them, too. But the alcoholic housewife can also make the family financially insecure. She can juggle charge accounts, manipulate the food budget, spend her afternoons gambling, and run her husband into debt by irresponsibility, waste, and extravagance.</p>

<p>But all alcoholics who have drunk themselves out of jobs, family, and friends will need to cross-examine themselves ruthlessly to determine how their own personality defects have thus demolished their security.</p>

<p><span class="highlight-problem">The most common symptoms of emotional insecurity are worry, anger, self-pity, and depression. These stem from causes which sometimes seem to be within us, and at other times to come from without.</span> To take inventory in this respect we ought to consider carefully all personal relationships which bring continuous or recurring trouble. It should be remembered that this kind of insecurity may arise in any area where instincts are threatened. Questioning directed to this end might run like this: Looking at both past and present, what sex situations have caused me anxiety, bitterness, frustration, or depression? Appraising each situation fairly, can I see where I have been at fault? Did these perplexities beset me because of selfishness or unreasonable demands? Or, if my disturbance was seemingly caused by the behavior of others, why do I lack the ability to accept conditions I cannot change? These are the sort of fundamental inquiries that can disclose the source of my discomfort and indicate whether I may be able to alter my own conduct and so adjust myself serenely to self-discipline.</p>

<p>Suppose that financial insecurity constantly arouses these same feelings. I can ask myself to what extent have my own mistakes fed my gnawing anxieties. And if the actions of others are part of the cause, what can I do about that? If I am unable to change the present state of affairs, am I willing to take the measures necessary to shape my life to conditions as they are? Questions like these, more of which will come to mind easily in each individual case, will help turn up the root causes.</p>

<p>But it is from our twisted relations with family, friends, and society at large that many of us have suffered the most. We have been especially stupid and stubborn about them. <span class="highlight-problem">The primary fact that we fail to recognize is our total inability to form a true partnership with another human being. Our egomania digs two disastrous pitfalls. Either we insist upon dominating the people we know, or we depend upon them far too much.</span> If we lean too heavily on people, they will sooner or later fail us, for they are human, too, and cannot possibly meet our incessant demands. In this way our insecurity grows and festers. When we habitually try to manipulate others to our own willful desires, they revolt, and resist us heavily. Then we develop hurt feelings, a sense of persecution, and a desire to retaliate. As we redouble our efforts at control, and continue to fail, our suffering becomes acute and constant. We have not once sought to be one in a family, to be a friend among friends, to be a worker among workers, to be a useful member of society. Always we tried to struggle to the top of the heap, or to hide underneath it. This self-centered behavior blocked a partnership relation with any one of those about us. Of true brotherhood we had small comprehension.</p>

<p>Some will object to many of the questions posed, because they think their own character defects have not been so glaring. To these it can be suggested that a conscientious examination is likely to reveal the very defects the objectionable questions are concerned with. Because our surface record hasn't looked too bad, we have frequently been abashed to find that this is so simply because we have buried these selfsame defects deep down in us under thick layers of self-justification. Whatever the defects, they have finally ambushed us into alcoholism and misery.</p>

<p><span class="highlight-action">Therefore, thoroughness ought to be the watchword when taking inventory. In this connection, it is wise to write out our questions and answers. It will be an aid to clear thinking and honest appraisal. It will be the first tangible evidence of our complete willingness to move forward.</span></p>
</div>
`,

  'step-five': `
<h2 class="text-xl font-semibold text-white mb-2">Step Five</h2>
<p class="text-teal-400 italic mb-6">"Admitted to God, to ourselves, and to another human being the exact nature of our wrongs."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>ALL OF A.A.'s Twelve Steps ask us to go contrary to our natural desires . . . they all deflate our egos. When it comes to ego deflation, few Steps are harder to take than Five. But scarcely any Step is more necessary to longtime sobriety and peace of mind than this one.</p>

<p>A.A. experience has taught us we cannot live alone with our pressing problems and the character defects which cause or aggravate them. If we have swept the searchlight of Step Four back and forth over our careers, and it has revealed in stark relief those experiences we'd rather not remember, if we have come to know how wrong thinking and action have hurt us and others, then the need to quit living by ourselves with those tormenting ghosts of yesterday gets more urgent than ever. <span class="highlight-action">We have to talk to somebody about them.</span></p>

<p>So intense, though, is our fear and reluctance to do this, that many A.A.'s at first try to bypass Step Five. We search for an easier way—which usually consists of the general and fairly painless admission that when drinking we were sometimes bad actors. Then, for good measure, we add dramatic descriptions of that part of our drinking behavior which our friends probably know about anyhow.</p>

<p>But of the things which really bother and burn us, we say nothing. Certain distressing or humiliating memories, we tell ourselves, ought not be shared with anyone. These will remain our secret. Not a soul must ever know. We hope they'll go to the grave with us.</p>

<p><span class="highlight-problem">Yet if A.A.'s experience means anything at all, this is not only unwise, but is actually a perilous resolve. Few muddled attitudes have caused us more trouble than holding back on Step Five.</span> Some people are unable to stay sober at all; others will relapse periodically until they really clean house. Even A.A. old timers, sober for years, often pay dearly for skimping this Step. They will tell how they tried to carry the load alone; how much they suffered of irritability, anxiety, remorse, and depression; and how, unconsciously seeking relief, they would sometimes accuse even their best friends of the very character defects they themselves were trying to conceal. They always discovered that relief never came by confessing the sins of other people. Everybody had to confess his own.</p>

<p>This practice of admitting one's defects to another person is, of course, very ancient. It has been validated in every century, and it characterizes the lives of all spiritually centered and truly religious people. But today religion is by no means the sole advocate of this saving principle. Psychiatrists and psychologists point out the deep need every human being has for practical insight and knowledge of his own personality flaws and for a discussion of them with an understanding and trustworthy person. So far as alcoholics are concerned, A.A. would go even further. <span class="highlight-solution">Most of us would declare that without a fearless admission of our defects to another human being we could not stay sober. It seems plain that the grace of God will not enter to expel our destructive obsessions until we are willing to try this.</span></p>

<p>What are we likely to receive from Step Five? <span class="highlight-result">For one thing, we shall get rid of that terrible sense of isolation we've always had.</span> Almost without exception, alcoholics are tortured by loneliness. Even before our drinking got bad and people began to cut us off, nearly all of us suffered the feeling that we didn't quite belong. Either we were shy, and dared not draw near others, or we were apt to be noisy good fellows craving attention and companionship, but never getting it—at least to our way of thinking. There was always that mysterious barrier we could neither surmount nor understand. It was as if we were actors on a stage, suddenly realizing that we did not know a single line of our parts. That's one reason we loved alcohol too well. It did let us act extemporaneously. But even Bacchus boomeranged on us; we were finally struck down and left in terrified loneliness.</p>

<p>When we reached A.A., and for the first time in our lives stood among people who seemed to understand, the sense of belonging was tremendously exciting. We thought the isolation problem had been solved. But we soon discovered that while we weren't alone anymore in a social sense, we still suffered many of the old pangs of anxious apartness. Until we had talked with complete candor of our conflicts, and had listened to someone else do the same thing, we still didn't belong. <span class="highlight-result">Step Five was the answer. It was the beginning of true kinship with man and God.</span></p>

<p>This vital Step was also the means by which we began to get the feeling that we could be forgiven, no matter what we had thought or done. Often it was while working on this Step with our sponsors or spiritual advisers that we first felt truly able to forgive others, no matter how deeply we felt they had wronged us. Our moral inventory had persuaded us that all-round forgiveness was desirable, but it was only when we resolutely tackled Step Five that we inwardly knew we'd be able to receive forgiveness and give it, too.</p>

<p><span class="highlight-result">Another great dividend we may expect from confiding our defects to another human being is humility—a word often misunderstood. To those who have made progress in A.A., it amounts to a clear recognition of what and who we really are, followed by a sincere attempt to become what we could be.</span> Therefore, our first practical move toward humility must consist of recognizing our deficiencies. No defect can be corrected unless we clearly see what it is. But we shall have to do more than see. The objective look at ourselves we achieved in Step Four was, after all, only a look. All of us saw, for example, that we lacked honesty and tolerance, that we were beset at times by attacks of self-pity or delusions of personal grandeur. But while this was a humiliating experience, it didn't necessarily mean that we had yet acquired much actual humility. Though now recognized, our defects were still there. Something had to be done about them. And we soon found that we could not wish or will them away by ourselves.</p>

<p><span class="highlight-action">More realism and therefore more honesty about ourselves are the great gains we make under the influence of Step Five.</span> As we took inventory, we began to suspect how much trouble self-delusion had been causing us. This had brought a disturbing reflection. If all our lives we had more or less fooled ourselves, how could we now be so sure that we weren't still self-deceived? How could we be certain that we had made a true catalog of our defects and had really admitted them, even to ourselves? Because we were still bothered by fear, self-pity, and hurt feelings, it was probable we couldn't appraise ourselves fairly at all. Too much guilt and remorse might cause us to dramatize and exaggerate our shortcomings. Or anger and hurt pride might be the smoke screen under which we were hiding some of our defects while we blamed others for them. Possibly, too, we were still handicapped by many liabilities, great and small, we never knew we had.</p>

<p>Hence it was most evident that a solitary self-appraisal, and the admission of our defects based upon that alone, wouldn't be nearly enough. We'd have to have outside help if we were surely to know and admit the truth about ourselves—the help of God and another human being. <span class="highlight-action">Only by discussing ourselves, holding back nothing, only by being willing to take advice and accept direction could we set foot on the road to straight thinking, solid honesty, and genuine humility.</span></p>

<p>Yet many of us still hung back. We said, "Why can't 'God as we understand Him' tell us where we are astray? If the Creator gave us our lives in the first place, then He must know in every detail where we have since gone wrong. Why don't we make our admissions to Him directly? Why do we need to bring anyone else into this?"</p>

<p>At this stage, the difficulties of trying to deal rightly with God by ourselves are twofold. Though we may at first be startled to realize that God knows all about us, we are apt to get used to that quite quickly. Somehow, being alone with God doesn't seem as embarrassing as facing up to another person. <span class="highlight-solution">Until we actually sit down and talk aloud about what we have so long hidden, our willingness to clean house is still largely theoretical. When we are honest with another person, it confirms that we have been honest with ourselves and with God.</span></p>

<p>The second difficulty is this: what comes to us alone may be garbled by our own rationalization and wishful thinking. The benefit of talking to another person is that we can get his direct comment and counsel on our situation, and there can be no doubt in our minds what that advice is. Going it alone in spiritual matters is dangerous. How many times have we heard well-intentioned people claim the guidance of God when it was all too plain that they were sorely mistaken. Lacking both practice and humility, they had deluded themselves and were able to justify the most arrant nonsense on the ground that this was what God had told them. It is worth noting that people of very high spiritual development almost always insist on checking with friends or spiritual advisers the guidance they feel they have received from God. Surely, then, a novice ought not lay himself open to the chance of making foolish, perhaps tragic, blunders in this fashion. While the comment or advice of others may be by no means infallible, it is likely to be far more specific than any direct guidance we may receive while we are still so inexperienced in establishing contact with a Power greater than ourselves.</p>

<p>Our next problem will be to discover the person in whom we are to confide. Here we ought to take much care, remembering that prudence is a virtue which carries a high rating. Perhaps we shall need to share with this person facts about ourselves which no others ought to know. We shall want to speak with someone who is experienced, who not only has stayed dry but has been able to surmount other serious difficulties. Difficulties, perhaps, like our own. This person may turn out to be one's sponsor, but not necessarily so. If you have developed a high confidence in him, and his temperament and problems are close to your own, then such a choice will be good. Besides, your sponsor already has the advantage of knowing something about your case.</p>

<p>Perhaps, though, your relation to him is such that you would care to reveal only a part of your story. If this is the situation, by all means do so, for you ought to make a beginning as soon as you can. It may turn out, however, that you'll choose someone else for the more difficult and deeper revelations. This individual may be entirely outside of A.A.—for example, your clergyman or your doctor. For some of us, a complete stranger may prove the best bet.</p>

<p>The real tests of the situation are your own willingness to confide and your full confidence in the one with whom you share your first accurate self-survey. Even when you've found the person, it frequently takes great resolution to approach him or her. No one ought to say the A.A. program requires no willpower; here is one place you may require all you've got. Happily, though, the chances are that you will be in for a very pleasant surprise. When your mission is carefully explained, and it is seen by the recipient of your confidence how helpful he can really be, the conversation will start easily and will soon become eager. Before long, your listener may well tell a story or two about himself which will place you even more at ease. <span class="highlight-result">Provided you hold back nothing, your sense of relief will mount from minute to minute. The dammed-up emotions of years break out of their confinement, and miraculously vanish as soon as they are exposed. As the pain subsides, a healing tranquility takes its place.</span> And when humility and serenity are so combined, something else of great moment is apt to occur. Many an A.A., once agnostic or atheistic, tells us that it was during this stage of Step Five that he first actually felt the presence of God. And even those who had faith already often become conscious of God as they never were before.</p>

<p><span class="highlight-result">This feeling of being at one with God and man, this emerging from isolation through the open and honest sharing of our terrible burden of guilt, brings us to a resting place where we may prepare ourselves for the following Steps toward a full and meaningful sobriety.</span></p>
</div>
`
};

export default chapterContent2;