export const chapterContent11 = {
  'tradition-ten': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Ten</h2>
<p class="text-teal-400 italic mb-6">"Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-result">NEVER since it began has Alcoholics Anonymous been divided by a major controversial issue. Nor has our Fellowship ever publicly taken sides on any question in an embattled world.</span> This, however, has been no earned virtue. It could almost be said that we were born with it, for, as one oldtimer recently declared, "Practically never have I heard a heated religious, political, or reform argument among A.A. members. So long as we don't argue these matters privately, it's a cinch we never shall publicly."</p>

<p><span class="highlight-solution">As by some deep instinct, we A.A.'s have known from the very beginning that we must never, no matter what the provocation, publicly take sides in any fight, even a worthy one.</span> All history affords us the spectacle of striving nations and groups finally torn asunder because they were designed for, or tempted into, controversy. Others fell apart because of sheer self-righteousness while trying to enforce upon the rest of mankind some millennium of their own specification. In our own times, we have seen millions die in political and economic wars often spurred by religious and racial difference. We live in the imminent possibility of a fresh holocaust to determine how men shall be governed, and how the products of nature and toil shall be divided among them. That is the spiritual climate in which A.A. was born, and by God's grace has nevertheless flourished.</p>

<p>Let us reemphasize that this reluctance to fight one another or anybody else is not counted as some special virtue which makes us feel superior to other people. Nor does it mean that the members of Alcoholics Anonymous, now restored as citizens of the world, are going to back away from their individual responsibilities to act as they see the right upon issues of our time. <span class="highlight-action">But when it comes to A.A. as a whole, that's quite a different matter. In this respect, we do not enter into public controversy, because we know that our Society will perish if it does.</span> We conceive the survival and spread of Alcoholics Anonymous to be something of far greater importance than the weight we could collectively throw back of any other cause. Since recovery from alcoholism is life itself to us, it is imperative that we preserve in full strength our means of survival.</p>

<p>Maybe this sounds as though the alcoholics in A.A. had suddenly gone peaceable, and become one great big happy family. Of course, this isn't so at all. Human beings that we are, we squabble. Before we leveled off a bit, A.A. looked more like one prodigious squabble than anything else, at least on the surface. A corporation director who had just voted a company expenditure of a hundred thousand dollars would appear at an A.A. business meeting and blow his top over an outlay of twenty-five dollars' worth of needed postage stamps. Disliking the attempt of some to manage a group, half its membership might angrily rush off to form another group more to their liking. Elders, temporarily turned Pharisee, have sulked. Bitter attacks have been directed against people suspected of mixed motives. <span class="highlight-result">Despite their din, our puny rows never did A.A. a particle of harm. They were just part and parcel of learning to work and live together. Let it be noted, too, that they were almost always concerned with ways to make A.A. more effective, how to do the most good for the most alcoholics.</span></p>

<p><span class="highlight-problem">The Washingtonian Society, a movement among alcoholics which started in Baltimore a century ago, almost discovered the answer to alcoholism. At first, the society was composed entirely of alcoholics trying to help one another. The early members foresaw that they should dedicate themselves to this sole aim. In many respects, the Washingtonians were akin to A.A. of today. Their membership passed the hundred thousand mark. Had they been left to themselves, and had they stuck to their one goal, they might have found the rest of the answer. But this didn't happen. Instead, the Washingtonians permitted politicians and reformers, both alcoholic and nonalcoholic, to use the society for their own purposes.</span> Abolition of slavery, for example, was a stormy political issue then. Soon, Washingtonian speakers violently and publicly took sides on this question. Maybe the society could have survived the abolition controversy, but it didn't have a chance from the moment it determined to reform America's drinking habits. When the Washingtonians became temperance crusaders, within a very few years they had completely lost their effectiveness in helping alcoholics.</p>

<p><span class="highlight-result">The lesson to be learned from the Washingtonians was not overlooked by Alcoholics Anonymous. As we surveyed the wreck of that movement, early A.A. members resolved to keep our Society out of public controversy. Thus was laid the cornerstone for Tradition Ten: "Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy."</span></p>
</div>
`,

  'tradition-eleven': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Eleven</h2>
<p class="text-teal-400 italic mb-6">"Our public relations policy is based on attraction rather than promotion; we need always maintain personal anonymity at the level of press, radio and films."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-result">WITHOUT its legions of well-wishers, A.A. could never have grown as it has. Throughout the world, immense and favorable publicity of every description has been the principal means of bringing alcoholics into our Fellowship.</span> In A.A. offices, clubs, and homes, telephones ring constantly. One voice says, "I read a piece in the newspapers . . ."; another, "We heard a radio program . . ."; and still another, "We saw a moving picture . . ." or "We saw something about A.A. on television. . . ." It is no exaggeration to say that half of A.A.'s membership has been led to us through channels like these.</p>

<p>The inquiring voices are not all alcoholics or their families. Doctors read medical papers about Alcoholics Anonymous and call for more information. Clergymen see articles in their church journals and also make inquiries. Employers learn that great corporations have set their approval upon us, and wish to discover what can be done about alcoholism in their own firms.</p>

<p>Therefore, a great responsibility fell upon us to develop the best possible public relations policy for Alcoholics Anonymous. Through many painful experiences, we think we have arrived at what that policy ought to be. <span class="highlight-solution">It is the opposite in many ways of usual promotional practice. We found that we had to rely upon the principle of attraction rather than of promotion.</span></p>

<p>Let's see how these two contrasting ideas—attraction and promotion—work out. A political party wishes to win an election, so it advertises the virtues of its leadership to draw votes. A worthy charity wants to raise money; forthwith, its letterhead shows the name of every distinguished person whose support can be obtained. Much of the political, economic, and religious life of the world is dependent upon publicized leadership. People who symbolize causes and ideas fill a deep human need. We of A.A. do not question that. <span class="highlight-problem">But we do have to soberly face the fact that being in the public eye is hazardous, especially for us. By temperament, nearly every one of us had been an irrepressible promoter, and the prospect of a society composed almost entirely of promoters was frightening.</span> Considering this explosive factor, we knew we had to exercise self-restraint.</p>

<p><span class="highlight-result">The way this restraint paid off was startling. It resulted in more favorable publicity of Alcoholics Anonymous than could possibly have been obtained through all the arts and abilities of A.A.'s best press agents.</span> Obviously, A.A. had to be publicized somehow, so we resorted to the idea that it would be far better to let our friends do this for us. Precisely that has happened, to an unbelievable extent. Veteran newsmen, trained doubters that they are, have gone all out to carry A.A.'s message. To them, we are something more than the source of good stories. On almost every newsfront, the men and women of the press have attached themselves to us as friends.</p>

<p>In the beginning, the press could not understand our refusal of all personal publicity. They were genuinely baffled by our insistence upon anonymity. Then they got the point. <span class="highlight-solution">Here was something rare in the world—a society which said it wished to publicize its principles and its work, but not its individual members.</span> The press was delighted with this attitude. Ever since, these friends have reported A.A. with an enthusiasm which the most ardent members would find hard to match.</p>

<p>There was actually a time when the press of America thought the anonymity of A.A. was better for us than some of our own members did. At one point, about a hundred of our Society were breaking anonymity at the public level. With perfectly good intent, these folks declared that the principle of anonymity was horse-and-buggy stuff, something appropriate to A.A.'s pioneering days. They were sure that A.A. could go faster and farther if it availed itself of modern publicity methods. A.A., they pointed out, included many persons of local, national, or international fame. Provided they were willing—and many were—why shouldn't their membership be publicized, thereby encouraging others to join us? These were plausible arguments, but happily our friends of the writing profession disagreed with them.</p>

<p>The Foundation wrote letters to practically every news outlet in North America, setting forth our public relations policy of attraction rather than promotion, and emphasizing personal anonymity. Since that time, editors and rewrite men have repeatedly deleted names and pictures of members from A.A. copy; frequently, they have reminded ambitious individuals of A.A.'s anonymity policy. They have even sacrificed good stories to this end. The force of their cooperation has certainly helped. Only a few A.A. members are left who deliberately break anonymity at the public level.</p>

<p><span class="highlight-result">This, in brief, is the process by which A.A.'s Tradition Eleven was constructed. To us, however, it represents far more than a sound public relations policy. It is more than a denial of self-seeking. This Tradition is a constant and practical reminder that personal ambition has no place in A.A. In it, each member becomes an active guardian of our Fellowship.</span></p>
</div>
`,

  'tradition-twelve': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Twelve</h2>
<p class="text-teal-400 italic mb-6">"Anonymity is the spiritual foundation of all our traditions, ever reminding us to place principles before personalities."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-solution">THE spiritual substance of anonymity is sacrifice. Because A.A.'s Twelve Traditions repeatedly ask us to give up personal desires for the common good, we realize that the sacrificial spirit—well symbolized by anonymity—is the foundation of them all.</span> It is A.A.'s proved willingness to make these sacrifices that gives people their high confidence in our future.</p>

<p>But in the beginning, anonymity was not born of confidence; it was the child of our early fears. Our first nameless groups of alcoholics were secret societies. New prospects could find us only through a few trusted friends. The bare hint of publicity, even for our work, shocked us. Though ex-drinkers, we still thought we had to hide from public distrust and contempt.</p>

<p>When the Big Book appeared in 1939, we called it "Alcoholics Anonymous." Its foreword made this revealing statement: "It is important that we remain anonymous because we are too few, at present, to handle the overwhelming number of personal appeals which may result from this publication. Being mostly business or professional folk, we could not well carry on our occupations in such an event." Between these lines, it is easy to read our fear that large numbers of incoming people might break our anonymity wide open.</p>

<p><span class="highlight-problem">As the A.A. groups multiplied, so did anonymity problems. Enthusiastic over the spectacular recovery of a brother alcoholic, we'd sometimes discuss those intimate and harrowing aspects of his case meant for his sponsor's ear alone. The aggrieved victim would then tightly declare that his trust had been broken.</span> When such stories got into circulation outside of A.A., the loss of confidence in our anonymity promise was severe. It frequently turned people from us. Clearly, every A.A. member's name—and story, too—had to be confidential, if he wished. This was our first lesson in the practical application of anonymity.</p>

<p>With characteristic intemperance, however, some of our newcomers cared not at all for secrecy. They wanted to shout A.A. from the housetops, and did. Alcoholics barely dry rushed about bright-eyed, buttonholing anyone who would listen to their stories. Others hurried to place themselves before microphones and cameras. Sometimes, they got distressingly drunk and let their groups down with a bang. They had changed from A.A. members into A.A. show-offs.</p>

<p>This phenomenon of contrast really set us thinking. Squarely before us was the question "How anonymous should an A.A. member be?" Our growth made it plain that we couldn't be a secret society, but it was equally plain that we couldn't be a vaudeville circuit, either. The charting of a safe path between these extremes took a long time.</p>

<p>As a rule, the average newcomer wanted his family to know immediately what he was trying to do. He also wanted to tell others who had tried to help him—his doctor, his minister, and close friends. As he gained confidence, he felt it right to explain his new way of life to his employer and business associates. When opportunities to be helpful came along, he found he could talk easily about A.A. to almost anyone. <span class="highlight-action">These quiet disclosures helped him to lose his fear of the alcoholic stigma, and spread the news of A.A.'s existence in his community.</span> Many a new man and woman came to A.A. because of such conversations. Though not in the strict letter of anonymity, such communications were well within its spirit.</p>

<p>But it became apparent that the word-of-mouth method was too limited. Our work, as such, needed to be publicized. The A.A. groups would have to reach quickly as many despairing alcoholics as they could. Consequently, many groups began to hold meetings which were open to interested friends and the public, so that the average citizen could see for himself just what A.A. was all about. The response to these meetings was warmly sympathetic. Soon, groups began to receive requests for A.A. speakers to appear before civic organizations, church groups, and medical societies. Provided anonymity was maintained on these platforms, and reporters present were cautioned against the use of names or pictures, the result was fine.</p>

<p>Then came our first few excursions into major publicity, which were breathtaking. Cleveland's Plain Dealer articles about us ran that town's membership from a few into hundreds overnight. The news stories of Mr. Rockefeller's dinner for Alcoholics Anonymous helped double our total membership in a year's time. Jack Alexander's famous Saturday Evening Post piece made A.A. a national institution. Such tributes as these brought opportunities for still more recognition. Other newspapers and magazines wanted A.A. stories. Film companies wanted to photograph us. Radio, and finally television, besieged us with requests for appearances. What should we do?</p>

<p><span class="highlight-action">As this tide offering top public approval swept in, we realized that it could do us incalculable good or great harm. Everything would depend upon how it was channeled. We simply couldn't afford to take the chance of letting self-appointed members present themselves as messiahs representing A.A. before the whole public.</span> The promoter instinct in us might be our undoing. If even one publicly got drunk, or was lured into using A.A.'s name for his own purposes, the damage might be irreparable. At this altitude (press, radio, films, and television), anonymity—100 percent anonymity—was the only possible answer. Here, principles would have to come before personalities, without exception.</p>

<p><span class="highlight-result">These experiences taught us that anonymity is real humility at work. It is an all-pervading spiritual quality which today keynotes A.A. life everywhere. Moved by the spirit of anonymity, we try to give up our natural desires for personal distinction as A.A. members both among fellow alcoholics and before the general public. As we lay aside these very human aspirations, we believe that each of us takes part in the weaving of a protective mantle which covers our whole Society and under which we may grow and work in unity.</span></p>

<p><span class="highlight-solution">We are sure that humility, expressed by anonymity, is the greatest safeguard that Alcoholics Anonymous can ever have.</span></p>
</div>
`,

  'traditions-long-form': `
<h2 class="text-xl font-semibold text-white mb-6">The Twelve Traditions — Long Form</h2>

<div class="prose prose-invert prose-slate max-w-none">
<p class="italic text-slate-400 mb-8">Our A.A. experience has taught us that:</p>

<div class="space-y-6">
<p><span class="text-teal-400 font-semibold">One</span> — Each member of Alcoholics Anonymous is but a small part of a great whole. A.A. must continue to live or most of us will surely die. Hence our common welfare comes first. But individual welfare follows close afterward.</p>

<p><span class="text-teal-400 font-semibold">Two</span> — For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience.</p>

<p><span class="text-teal-400 font-semibold">Three</span> — Our membership ought to include all who suffer from alcoholism. Hence we may refuse none who wish to recover. Nor ought A.A. membership ever depend on money or conformity. Any two or three alcoholics gathered together for sobriety may call themselves an A.A. group, provided that, as a group, they have no other affiliation.</p>

<p><span class="text-teal-400 font-semibold">Four</span> — With respect to its own affairs, each A.A. group should be responsible to no other authority other than its own conscience. But when its plans concern the welfare of neighboring groups also, those groups ought to be consulted. And no group, regional committee, or individual should ever take any action that might greatly affect A.A. as a whole without conferring with the trustees of the General Service Board. On such issues our common welfare is paramount.</p>

<p><span class="text-teal-400 font-semibold">Five</span> — Each Alcoholics Anonymous group ought to be a spiritual entity having but one primary purpose—that of carrying its message to the alcoholic who still suffers.</p>

<p><span class="text-teal-400 font-semibold">Six</span> — Problems of money, property, and authority may easily divert us from our primary spiritual aim. We think, therefore, that any considerable property of genuine use to A.A. should be separately incorporated and managed, thus dividing the material from the spiritual. An A.A. group, as such, should never go into business. Secondary aids to A.A. such as clubs or hospitals which require much property or administration, ought to be incorporated and so set apart that, if necessary, they can be freely discarded by the groups. Hence such facilities ought not to use the A.A. name. Their management should be the sole responsibility of those people who financially support them. For clubs, A.A. managers are usually preferred. But hospitals, as well as other places of recuperation, ought to be well outside A.A.—and medically supervised. While an A.A. group may cooperate with anyone, such cooperation ought never to go so far as affiliation or endorsement, actual or implied. An A.A. group can bind itself to no one.</p>

<p><span class="text-teal-400 font-semibold">Seven</span> — The A.A. groups themselves ought to be fully supported by the voluntary contributions of their own members. We think that each group should soon achieve this ideal; that any public solicitation of funds using the name of Alcoholics Anonymous is highly dangerous whether by groups, clubs, hospitals, or other outside agencies; that acceptance of large gifts from any source, or of contributions carrying any obligation whatever, is unwise. Then, too, we view with much concern those A.A. treasuries which continue, beyond prudent reserves, to accumulate funds for no stated A.A. purpose. Experience has often warned us that nothing can so surely destroy our spiritual heritage as futile disputes over property, money, and authority.</p>

<p><span class="text-teal-400 font-semibold">Eight</span> — Alcoholics Anonymous should remain forever nonprofessional. We define professionalism as the occupation of counseling alcoholics for fees or hire. But we may employ alcoholics where they are going to perform those services for which we might otherwise have to engage nonalcoholics. Such special services may be well recompensed. But our usual A.A. Twelfth Step work is never to be paid for.</p>

<p><span class="text-teal-400 font-semibold">Nine</span> — Each A.A. group needs the least possible organization. Rotating leadership is the best. The small group may elect its secretary, the large group its rotating committee, and the groups of a large metropolitan area their central or intergroup committee, which often employs a full-time secretary. The trustees of the General Service Board are, in effect, our A.A. General Service Committee. They are the custodians of our A.A. Tradition and the receivers of voluntary A.A. contributions by which we maintain our A.A. General Service Office in New York. They are authorized by the groups to handle our overall public relations, and they guarantee the integrity of our principal newspaper, the A.A. Grapevine. All such representatives are to be guided in the spirit of service, for true leaders in A.A. are but trusted and experienced servants of the whole. They derive no real authority from their titles; they do not govern. Universal respect is the key to their usefulness.</p>

<p><span class="text-teal-400 font-semibold">Ten</span> — No A.A. group or member should ever, in such a way as to implicate A.A., express any opinion on outside controversial issues—particularly those of politics, alcohol reform, or sectarian religion. The Alcoholics Anonymous groups oppose no one. Concerning such matters they can express no views whatsoever.</p>

<p><span class="text-teal-400 font-semibold">Eleven</span> — Our relations with the general public should be characterized by personal anonymity. We think A.A. should avoid sensational advertising. Our names and pictures as A.A. members ought not be broadcast, filmed, or publicly printed. Our public relations should be guided by the principle of attraction rather than promotion. There is never need to praise ourselves. We feel it better that our friends recommend us.</p>

<p><span class="text-teal-400 font-semibold">Twelve</span> — And finally, we of Alcoholics Anonymous believe that the principle of anonymity has an immense spiritual significance. It reminds us that we are to place principles before personalities; that we are to practice a genuine humility. This to the end that our great blessings may never spoil us; that we shall forever live in thankful contemplation of Him who presides over us all.</p>
</div>
</div>
`
};

export default chapterContent11;