export const chapterContent8 = {
  'tradition-one': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition One</h2>
<p class="text-teal-400 italic mb-6">"Our common welfare should come first; personal recovery depends upon A.A. unity."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-solution">THE unity of Alcoholics Anonymous is the most cherished quality our Society has. Our lives, the lives of all to come, depend squarely upon it. We stay whole, or A.A. dies.</span> Without unity, the heart of A.A. would cease to beat; our world arteries would no longer carry the life-giving grace of God; His gift to us would be spent aimlessly. Back again in their caves, alcoholics would reproach us and say, "What a great thing A.A. might have been!"</p>

<p>"Does this mean," some will anxiously ask, "that in A.A. the individual doesn't count for much? Is he to be dominated by his group and swallowed up in it?"</p>

<p>We may certainly answer this question with a loud "No!" We believe there isn't a fellowship on earth which lavishes more devoted care upon its individual members; surely there is none which more jealously guards the individual's right to think, talk, and act as he wishes. No A.A. can compel another to do anything; nobody can be punished or expelled. Our Twelve Steps to recovery are suggestions; the Twelve Traditions which guarantee A.A.'s unity contain not a single "Don't." They repeatedly say "We ought . . ." but never "You must!"</p>

<p>To many minds all this liberty for the individual spells sheer anarchy. Every newcomer, every friend who looks at A.A. for the first time is greatly puzzled. They see liberty verging on license, yet they recognize at once that A.A. has an irresistible strength of purpose and action. "How," they ask, "can such a crowd of anarchists function at all? How can they possibly place their common welfare first? What in Heaven's name holds them together?"</p>

<p>Those who look closely soon have the key to this strange paradox. <span class="highlight-action">The A.A. member has to conform to the principles of recovery. His life actually depends upon obedience to spiritual principles. If he deviates too far, the penalty is sure and swift; he sickens and dies.</span> At first he goes along because he must, but later he discovers a way of life he really wants to live. Moreover, he finds he cannot keep this priceless gift unless he gives it away. Neither he nor anybody else can survive unless he carries the A.A. message. The moment this Twelfth Step work forms a group, another discovery is made—that most individuals cannot recover unless there is a group. Realization dawns that he is but a small part of a great whole; that no personal sacrifice is too great for preservation of the Fellowship. He learns that the clamor of desires and ambitions within him must be silenced whenever these could damage the group. <span class="highlight-result">It becomes plain that the group must survive or the individual will not.</span></p>

<p>So at the outset, how best to live and work together as groups became the prime question. In the world about us we saw personalities destroying whole peoples. The struggle for wealth, power, and prestige was tearing humanity apart as never before. If strong people were stalemated in the search for peace and harmony, what was to become of our erratic band of alcoholics? As we had once struggled and prayed for individual recovery, just so earnestly did we commence to quest for the principles through which A.A. itself might survive. On anvils of experience, the structure of our Society was hammered out.</p>

<p>Countless times, in as many cities and hamlets, we reenacted the story of Eddie Rickenbacker and his courageous company when their plane crashed in the Pacific. Like us, they had suddenly found themselves saved from death, but still floating upon a perilous sea. How well they saw that their common welfare came first. None might become selfish of water or bread. Each needed to consider the others, and in abiding faith they knew they must find their real strength. And this they did find, in measure to transcend all the defects of their frail craft, every test of uncertainty, pain, fear, and despair, and even the death of one.</p>

<p><span class="highlight-result">Thus has it been with A.A. By faith and by works we have been able to build upon the lessons of an incredible experience. They live today in the Twelve Traditions of Alcoholics Anonymous, which—God willing—shall sustain us in unity for so long as He may need us.</span></p>
</div>
`,

  'tradition-two': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Two</h2>
<p class="text-teal-400 italic mb-6">"For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience. Our leaders are but trusted servants; they do not govern."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>WHERE does A.A. get its direction? Who runs it? This, too, is a puzzler for every friend and newcomer. When told that our Society has no president having authority to govern it, no treasurer who can compel the payment of any dues, no board of directors who can cast an erring member into outer darkness, when indeed no A.A. can give another a directive and enforce obedience, our friends gasp and exclaim, "This simply can't be. There must be an angle somewhere." These practical folk then read Tradition Two, and learn that <span class="highlight-solution">the sole authority in A.A. is a loving God as He may express Himself in the group conscience.</span> They dubiously ask an experienced A.A. member if this really works. The member, sane to all appearances, immediately answers, "Yes! It definitely does." The friends mutter that this looks vague, nebulous, pretty naive to them. Then they commence to watch us with speculative eyes, pick up a fragment of A.A. history, and soon have the solid facts.</p>

<p>What are these facts of A.A. life which brought us to this apparently impractical principle?</p>

<p>John Doe, a good A.A., moves—let us say—to Middletown, U.S.A. Alone now, he reflects that he may not be able to stay sober, or even alive, unless he passes on to other alcoholics what was so freely given him. He feels a spiritual and ethical compulsion, because hundreds may be suffering within reach of his help. Then, too, he misses his home group. He needs other alcoholics as much as they need him. He visits preachers, doctors, editors, policemen, and bartenders . . . with the result that Middletown now has a group, and he is the founder.</p>

<p>Being the founder, he is at first the boss. Who else could be? Very soon, though, his assumed authority to run everything begins to be shared with the first alcoholics he has helped. At this moment, the benign dictator becomes the chairman of a committee composed of his friends. These are the growing group's hierarchy of service—self-appointed, of course, because there is no other way. In a matter of months, A.A. booms in Middletown.</p>

<p>The founder and his friends channel spirituality to newcomers, hire halls, make hospital arrangements, and entreat their wives to brew gallons of coffee. Being on the human side, the founder and his friends may bask a little in glory. They say to one another, "Perhaps it would be a good idea if we continue to keep a firm hand on A.A. in this town. After all, we are experienced. Besides, look at all the good we've done these drunks. They should be grateful!" True, founders and their friends are sometimes wiser and more humble than this. But more often at this stage they are not.</p>

<p><span class="highlight-problem">Growing pains now beset the group. Panhandlers panhandle. Lonely hearts pine. Problems descend like an avalanche.</span> Still more important, murmurs are heard in the body politic, which swell into a loud cry: "Do these old-timers think they can run this group forever? Let's have an election." The founder and his friends are hurt and depressed. They rush from crisis to crisis and from member to member, pleading; but it's no use, the revolution is on. The group conscience is about to take over.</p>

<p>Now comes the election. If the founder and his friends have served well, they may—to their surprise—be reinstated for a time. If, however, they have heavily resisted the rising tide of democracy, they may be summarily beached. In either case, the group now has a so-called rotating committee, very sharply limited in its authority. <span class="highlight-action">In no sense whatever can its members govern or direct the group. They are servants. Theirs is the sometimes thankless privilege of doing the group's chores.</span> Headed by the chairman, they look after public relations and arrange meetings. Their treasurer, strictly accountable, takes money from the hat that is passed, banks it, pays the rent and other bills, and makes a regular report at business meetings. The secretary sees that literature is on the table, looks after the phone-answering service, answers the mail, and sends out notices of meetings. Such are the simple services that enable the group to function. The committee gives no spiritual advice, judges no one's conduct, issues no orders. Every one of them may be promptly eliminated at the next election if they try this. And so they make the belated discovery that they are really servants, not senators. These are universal experiences. Thus throughout A.A. does the group conscience decree the terms upon which its leaders shall serve.</p>

<p>This brings us straight to the question "Does A.A. have a real leadership?" Most emphatically the answer is "Yes, notwithstanding the apparent lack of it." Let's turn again to the deposed founder and his friends. What becomes of them? As their grief and anxiety wear away, a subtle change begins. Ultimately, they divide into two classes known in A.A. slang as "elder statesmen" and "bleeding deacons." <span class="highlight-solution">The elder statesman is the one who sees the wisdom of the group's decision, who holds no resentment over his reduced status, whose judgment, fortified by considerable experience, is sound, and who is willing to sit quietly on the sidelines patiently awaiting developments.</span> <span class="highlight-problem">The bleeding deacon is one who is just as surely convinced that the group cannot get along without him, who constantly connives for reelection to office, and who continues to be consumed with self-pity.</span> A few hemorrhage so badly that—drained of all A.A. spirit and principle—they get drunk. At times the A.A. landscape seems to be littered with bleeding forms. Nearly every oldtimer in our Society has gone through this process in some degree. Happily, most of them survive and live to become elder statesmen. They become the real and permanent leadership of A.A. Theirs is the quiet opinion, the sure knowledge and humble example that resolve a crisis. When sorely perplexed, the group inevitably turns to them for advice. <span class="highlight-result">They become the voice of the group conscience; in fact, these are the true voice of Alcoholics Anonymous. They do not drive by mandate; they lead by example.</span> This is the experience which has led us to the conclusion that our group conscience, well-advised by its elders, will be in the long run wiser than any single leader.</p>

<p>When A.A. was only three years old, an event occurred demonstrating this principle. One of the first members of A.A., entirely contrary to his own desires, was obliged to conform to group opinion. Here is the story in his words.</p>

<p>"One day I was doing a Twelfth Step job at a hospital in New York. The proprietor, Charlie, summoned me to his office. 'Bill,' he said, 'I think it's a shame that you are financially so hard up. All around you these drunks are getting well and making money. But you're giving this work full time, and you're broke. It isn't fair.' Charlie fished in his desk and came up with an old financial statement. Handing it to me, he continued, 'This shows the kind of money the hospital used to make back in the 1920's. Thousands of dollars a month. It should be doing just as well now, and it would—if only you'd help me. So why don't you move your work in here? I'll give you an office, a decent drawing account, and a very healthy slice of the profits. Three years ago, when my head doctor, Silkworth, began to tell me of the idea of helping drunks by spirituality, I thought it was crackpot stuff, but I've changed my mind. Some day this bunch of ex-drunks of yours will fill Madison Square Garden, and I don't see why you should starve meanwhile. What I propose is perfectly ethical. You can become a lay therapist, and more successful than anybody in the business.'</p>

<p>"I was bowled over. There were a few twinges of conscience until I saw how really ethical Charlie's proposal was. There was nothing wrong whatever with becoming a lay therapist. I thought of Lois coming home exhausted from the department store each day, only to cook supper for a houseful of drunks who weren't paying board. I thought of the large sum of money still owing my Wall Street creditors. I thought of a few of my alcoholic friends, who were making as much money as ever. Why shouldn't I do as well as they?</p>

<p>"Although I asked Charlie for a little time to consider it, my own mind was about made up. Racing back to Brooklyn on the subway, I had a seeming flash of divine guidance. It was only a single sentence, but most convincing. In fact, it came right out of the Bible—a voice kept saying to me, 'The laborer is worthy of his hire.' Arriving home, I found Lois cooking as usual, while three drunks looked hungrily on from the kitchen door. I drew her aside and told the glorious news. She looked interested, but not as excited as I thought she should be.</p>

<p>"It was meeting night. Although none of the alcoholics we boarded seemed to get sober, some others had. With their wives they crowded into our downstairs parlor. At once I burst into the story of my opportunity. Never shall I forget their impassive faces, and the steady gaze they focused upon me. With waning enthusiasm, my tale trailed off to the end. There was a long silence.</p>

<p>"Almost timidly, one of my friends began to speak. 'We know how hard up you are, Bill. It bothers us a lot. We've often wondered what we might do about it. But I think I speak for everyone here when I say that what you now propose bothers us an awful lot more.' The speaker's voice grew more confident. 'Don't you realize,' he went on, 'that you can never become a professional? As generous as Charlie has been to us, don't you see that we can't tie this thing up with his hospital or any other? You tell us that Charlie's proposal is ethical. Sure, it's ethical, but what we've got won't run on ethics only; it has to be better. Sure, Charlie's idea is good, but it isn't good enough. This is a matter of life and death, Bill, and nothing but the very best will do!' Challengingly, my friends looked at me as their spokesman continued. 'Bill, haven't you often said right here in this meeting that sometimes the good is the enemy of the best? Well, this is a plain case of it. You can't do this thing to us!'</p>

<p><span class="highlight-result">"So spoke the group conscience. The group was right and I was wrong; the voice on the subway was not the voice of God. Here was the true voice, welling up out of my friends. I listened, and—thank God—I obeyed."</span></p>
</div>
`,

  'tradition-three': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Three</h2>
<p class="text-teal-400 italic mb-6">"The only requirement for A.A. membership is a desire to stop drinking."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-solution">THIS Tradition is packed with meaning. For A.A. is really saying to every serious drinker, "You are an A.A. member if you say so. You can declare yourself in; nobody can keep you out. No matter who you are, no matter how low you've gone, no matter how grave your emotional complications—even your crimes—we still can't deny you A.A. We don't want to keep you out. We aren't a bit afraid you'll harm us, never mind how twisted or violent you may be. We just want to be sure that you get the same great chance for sobriety that we've had. So you're an A.A. member the minute you declare yourself."</span></p>

<p><span class="highlight-problem">To establish this principle of membership took years of harrowing experience. In our early time, nothing seemed so fragile, so easily breakable as an A.A. group. Hardly an alcoholic we approached paid any attention; most of those who did join us were like flickering candles in a windstorm. Time after time, their uncertain flames blew out and couldn't be relighted.</span> Our unspoken, constant thought was "Which of us may be the next?"</p>

<p>A member gives us a vivid glimpse of those days. "At one time," he says, "every A.A. group had many membership rules. Everybody was scared witless that something or somebody would capsize the boat and dump us all back into the drink. Our Foundation office asked each group to send in its list of 'protective' regulations. The total list was a mile long. If all those rules had been in effect everywhere, nobody could have possibly joined A.A. at all, so great was the sum of our anxiety and fear.</p>

<p>"We were resolved to admit nobody to A.A. but that hypothetical class of people we termed 'pure alcoholics.' Except for their guzzling, and the unfortunate results thereof, they could have no other complications. So beggars, tramps, asylum inmates, prisoners, queers, plain crackpots, and fallen women were definitely out. Yes sir, we'd cater only to pure and respectable alcoholics! Any others would surely destroy us. Besides, if we took in those odd ones, what would decent people say about us? We built a fine-mesh fence right around A.A.</p>

<p>"Maybe this sounds comical now. Maybe you think we oldtimers were pretty intolerant. But I can tell you there was nothing funny about the situation then. We were grim because we felt our lives and homes were threatened, and that was no laughing matter. Intolerant, you say? Well, we were frightened. Naturally, we began to act like most everybody does when afraid. After all, isn't fear the true basis of intolerance? Yes, we were intolerant."</p>

<p>How could we then guess that all those fears were to prove groundless? <span class="highlight-result">How could we know that thousands of these sometimes frightening people were to make astonishing recoveries and become our greatest workers and intimate friends? Was it credible that A.A. was to have a divorce rate far lower than average? Could we then foresee that troublesome people were to become our principal teachers of patience and tolerance? Could any then imagine a society which would include every conceivable kind of character, and cut across every barrier of race, creed, politics, and language with ease?</span></p>

<p>Why did A.A. finally drop all its membership regulations? Why did we leave it to each newcomer to decide himself whether he was an alcoholic and whether he should join us? Why did we dare to say, contrary to the experience of society and government everywhere, that we would neither punish nor deprive any A.A. of membership, that we must never compel anyone to pay anything, believe anything, or conform to anything?</p>

<p><span class="highlight-solution">The answer, now seen in Tradition Three, was simplicity itself. At last experience taught us that to take away any alcoholic's full chance was sometimes to pronounce his death sentence, and often to condemn him to endless misery. Who dared to be judge, jury, and executioner of his own sick brother?</span></p>

<p>As group after group saw these possibilities, they finally abandoned all membership regulations. One dramatic experience after another clinched this determination until it became our universal tradition. Here are two examples:</p>

<p>On the A.A. calendar it was Year Two. In that time nothing could be seen but two struggling, nameless groups of alcoholics trying to hold their faces up to the light.</p>

<p>A newcomer appeared at one of these groups, knocked on the door and asked to be let in. He talked frankly with that group's oldest member. He soon proved that his was a desperate case, and that above all he wanted to get well. "But," he asked, "will you let me join your group? Since I am the victim of another addiction even worse stigmatized than alcoholism, you may not want me among you. Or will you?"</p>

<p>There was the dilemma. What should the group do? The oldest member summoned two others, and in confidence laid the explosive facts in their laps. Said he, "Well, what about it? If we turn this man away, he'll soon die. If we allow him in, only God knows what trouble he'll brew. What shall the answer be—yes or no?"</p>

<p>At first the elders could look only at the objections. "We deal," they said, "with alcoholics only. Shouldn't we sacrifice this one for the sake of the many?" So went the discussion while the newcomer's fate hung in the balance.</p>

<p>Then one of the three spoke in a very different voice. <span class="highlight-action">"What we are really afraid of," he said, "is our reputation. We are much more afraid of what people might say than the trouble this strange alcoholic might bring. As we've been talking, five short words have been running through my mind. Something keeps repeating to me, 'What would the Master do?'"</span> Not another word was said. What more indeed could be said?</p>

<p>Overjoyed, the newcomer plunged into Twelfth Step work. Tirelessly he laid A.A.'s message before scores of people. Since this was a very early group, those scores have since multiplied themselves into thousands. Never did he trouble anyone with his other difficulty. <span class="highlight-result">A.A. had taken its first step in the formation of Tradition Three.</span></p>
</div>
`
};

export default chapterContent8;