export const chapterContent10 = {
  'tradition-eight': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Eight</h2>
<p class="text-teal-400 italic mb-6">"Alcoholics Anonymous should remain forever nonprofessional, but our service centers may employ special workers."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-solution">ALCOHOLICS ANONYMOUS will never have a professional class. We have gained some understanding of the ancient words "Freely ye have received, freely give." We have discovered that at the point of professionalism, money and spirituality do not mix.</span> Almost no recovery from alcoholism has ever been brought about by the world's best professionals, whether medical or religious. We do not decry professionalism in other fields, but we accept the sober fact that it does not work for us. Every time we have tried to professionalize our Twelfth Step, the result has been exactly the same: Our single purpose has been defeated.</p>

<p><span class="highlight-problem">Alcoholics simply will not listen to a paid twelfth-stepper.</span> Almost from the beginning, we have been positive that face-to-face work with the alcoholic who suffers could be based only on the desire to help and be helped. When an A.A. talks for money, whether at a meeting or to a single newcomer, it can have a very bad effect on him, too. The money motive compromises him and everything he says and does for his prospect. This has always been so obvious that only a very few A.A.'s have ever worked the Twelfth Step for a fee.</p>

<p>Despite this certainty, it is nevertheless true that few subjects have been the cause of more contention within our Fellowship than professionalism. Caretakers who swept floors, cooks who fried hamburgers, secretaries in offices, authors writing books—all these we have seen hotly assailed because they were, as their critics angrily remarked, "making money out of A.A." Ignoring the fact that these labors were not Twelfth Step jobs at all, the critics attacked as A.A. professionals these workers of ours who were often doing thankless tasks that no one else could or would do. Even greater furors were provoked when A.A. members began to run rest homes and farms for alcoholics, when some hired out to corporations as personnel men in charge of the alcoholic problem in industry, when some became nurses on alcoholic wards, when others entered the field of alcohol education. In all these instances, and more, it was claimed that A.A. knowledge and experience were being sold for money, hence these people, too, were professionals.</p>

<p><span class="highlight-solution">At last, however, a plain line of cleavage could be seen between professionalism and nonprofessionalism. When we had agreed that the Twelfth Step couldn't be sold for money, we had been wise. But when we had declared that our Fellowship couldn't hire service workers nor could any A.A. member carry our knowledge into other fields, we were taking the counsel of fear, fear which today has been largely dispelled in the light of experience.</span></p>

<p>Take the case of the club janitor and cook. If a club is going to function, it has to be habitable and hospitable. We tried volunteers, who were quickly disenchanted with sweeping floors and brewing coffee seven days a week. They just didn't show up. Even more important, an empty club couldn't answer its telephone, but it was an open invitation to a drunk on a binge who possessed a spare key. So somebody had to look after the place full time. If we hired an alcoholic, he'd receive only what we'd have to pay a nonalcoholic for the same job. <span class="highlight-action">The job was not to do Twelfth Step work; it was to make Twelfth Step work possible. It was a service proposition, pure and simple.</span></p>

<p>Neither could A.A. itself function without full-time workers. At the Foundation and intergroup offices, we couldn't employ nonalcoholics as secretaries; we had to have people who knew the A.A. pitch. But the minute we hired them, the ultraconservative and fearful ones shrilled, "Professionalism!" At one period, the status of these faithful servants was almost unbearable. They weren't asked to speak at A.A. meetings because they were "making money out of A.A." At times, they were actually shunned by fellow members. Even the charitably disposed described them as "a necessary evil." Committees took full advantage of this attitude to depress their salaries. They could regain some measure of virtue, it was thought, if they worked for A.A. real cheap. These notions persisted for years. Then we saw that if a hardworking secretary answered the phone dozens of times a day, listened to twenty wailing wives, arranged hospitalization and got sponsorship for ten newcomers, and was gently diplomatic with the irate drunk who complained about the job she was doing and how she was overpaid, then such a person could surely not be called a professional A.A. <span class="highlight-result">She was not professionalizing the Twelfth Step; she was just making it possible. She was helping to give the man coming in the door the break he ought to have.</span> Volunteer committeemen and assistants could be of great help, but they could not be expected to carry this load day in and day out.</p>

<p>At the Foundation, the same story repeats itself. Eight tons of books and literature per month do not package and channel themselves all over the world. Sacks of letters on every conceivable A.A. problem ranging from a lonely-heart Eskimo to the growing pains of thousands of groups must be answered by people who know. Right contacts with the world outside have to be maintained. A.A.'s lifelines have to be tended. So we hire A.A. staff members. We pay them well, and they earn what they get. They are professional secretaries, but they certainly are not professional A.A.'s.</p>

<p>Perhaps the fear will always lurk in every A.A. heart that one day our name will be exploited by somebody for real cash. Even the suggestion of such a thing never fails to whip up a hurricane, and we have discovered that hurricanes have a way of mauling with equal severity both the just and the unjust. They are always unreasonable.</p>

<p>No individuals have been more buffeted by such emotional gusts than those A.A.'s bold enough to accept employment with outside agencies dealing with the alcohol problem. A university wanted an A.A. member to educate the public on alcoholism. A corporation wanted a personnel man familiar with the subject. A state drunk farm wanted a manager who could really handle inebriates. A city wanted an experienced social worker who understood what alcohol could do to a family. A state alcohol commission wanted a paid researcher. These are only a few of the jobs which A.A. members as individuals have been asked to fill. Now and then, A.A. members have bought farms or rest homes where badly beat-up topers could find needed care. The question was—and sometimes still is—are such activities to be branded as professionalism under A.A. tradition?</p>

<p><span class="highlight-solution">We think the answer is "No. Members who select such full-time careers do not professionalize A.A.'s Twelfth Step."</span> The road to this conclusion was long and rocky. At first, we couldn't see the real issue involved. In former days, the moment an A.A. hired out to such enterprises, he was immediately tempted to use the name Alcoholics Anonymous for publicity or money-raising purposes. Drunk farms, educational ventures, state legislatures, and commissions advertised the fact that A.A. members served them. Unthinkingly, A.A.'s so employed recklessly broke anonymity to thump the tub for their pet enterprise. For this reason, some very good causes and all connected with them suffered unjust criticism from A.A. groups. More often than not, these onslaughts were spearheaded by the cry "Professionalism! That guy is making money out of A.A.!" Yet not a single one of them had been hired to do A.A.'s Twelfth Step work. The violation in these instances was not professionalism at all; it was breaking anonymity. A.A.'s sole purpose was being compromised, and the name of Alcoholics Anonymous was being misused.</p>

<p>It is significant, now that almost no A.A. in our Fellowship breaks anonymity at the public level, that nearly all these fears have subsided. We see that we have no right or need to discourage A.A.'s who wish to work as individuals in these wider fields. It would be actually antisocial were we to forbid them. We cannot declare A.A. such a closed corporation that we keep our knowledge and experience top secret. If an A.A. member acting as a citizen can become a better researcher, educator, personnel officer, then why not? Everybody gains and we have lost nothing. True, some of the projects to which A.A.'s have attached themselves have been ill-conceived, but that makes not the slightest difference with the principle involved.</p>

<p><span class="highlight-result">This is the exciting welter of events which has finally cast up A.A.'s Tradition of nonprofessionalism. Our Twelfth Step is never to be paid for, but those who labor in service for us are worthy of their hire.</span></p>
</div>
`,

  'tradition-nine': `
<h2 class="text-xl font-semibold text-white mb-2">Tradition Nine</h2>
<p class="text-teal-400 italic mb-6">"A.A., as such, ought never be organized; but we may create service boards or committees directly responsible to those they serve."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>WHEN Tradition Nine was first written, it said that "Alcoholics Anonymous needs the least possible organization." In years since then, we have changed our minds about that. <span class="highlight-solution">Today, we are able to say with assurance that Alcoholics Anonymous—A.A. as a whole—should never be organized at all.</span> Then, in seeming contradiction, we proceed to create special service boards and committees which in themselves are organized. How, then, can we have an unorganized movement which can and does create a service organization for itself? Scanning this puzzler, people say, "What do they mean, no organization?"</p>

<p>Well, let's see. Did anyone ever hear of a nation, a church, a political party, even a benevolent association that had no membership rules? Did anyone ever hear of a society which couldn't somehow discipline its members and enforce obedience to necessary rules and regulations? Doesn't nearly every society on earth give authority to some of its members to impose obedience upon the rest and to punish or expel offenders? Therefore, every nation, in fact every form of society, has to be a government administered by human beings. Power to direct or govern is the essence of organization everywhere.</p>

<p><span class="highlight-solution">Yet Alcoholics Anonymous is an exception. It does not conform to this pattern. Neither its General Service Conference, its Foundation Board, nor the humblest group committee can issue a single directive to an A.A. member and make it stick, let alone mete out any punishment.</span> We've tried it lots of times, but utter failure is always the result. Groups have tried to expel members, but the banished have come back to sit in the meeting place, saying, "This is life for us; you can't keep us out." Committees have instructed many an A.A. to stop working on a chronic backslider, only to be told: "How I do my Twelfth Step work is my business. Who are you to judge?" This doesn't mean an A.A. won't take advice or suggestions from more experienced members, but he surely won't take orders. Who is more unpopular than the oldtime A.A., full of wisdom, who moves to another area and tries to tell the group there how to run its business? He and all like him who "view with alarm for the good of A.A." meet the most stubborn resistance or, worse still, laughter.</p>

<p>You might think A.A.'s headquarters in New York would be an exception. Surely, the people there would have to have some authority. But long ago, trustees and staff members alike found they could do no more than make suggestions, and very mild ones at that. They even had to coin a couple of sentences which still go into half the letters they write: "Of course, you are at perfect liberty to handle this matter any way you please. But the majority experience in A.A. does seem to suggest . . ." Now, that attitude is far removed from central government, isn't it? We recognize that alcoholics can't be dictated to—individually or collectively.</p>

<p>At this juncture, we can hear a churchman exclaim, "They are making disobedience a virtue!" He is joined by a psychiatrist who says, "Defiant brats! They won't grow up and conform to social usage!" The man in the street says, "I don't understand it. They must be nuts!" But all these observers have overlooked something unique in Alcoholics Anonymous. <span class="highlight-action">Unless each A.A. member follows to the best of his ability our suggested Twelve Steps to recovery, he almost certainly signs his own death warrant. His drunkenness and dissolution are not penalties inflicted by people in authority; they result from his personal disobedience to spiritual principles.</span></p>

<p>The same stern threat applies to the group itself. Unless there is approximate conformity to A.A.'s Twelve Traditions, the group, too, can deteriorate and die. <span class="highlight-result">So we of A.A. do obey spiritual principles, first because we must, and ultimately because we love the kind of life such obedience brings. Great suffering and love are A.A.'s disciplinarians; we need no others.</span></p>

<p>It is clear now that we ought never to name boards to govern us, but it is equally clear that we shall always need to authorize workers to serve us. <span class="highlight-solution">It is the difference between the spirit of vested authority and the spirit of service, two concepts which are sometimes poles apart.</span> It is in this spirit of service that we elect the A.A. group's informal rotating committee, the intergroup association for the area, and the General Service Conferences of Alcoholics Anonymous for A.A. as a whole. Even our Foundation, once an independent board, is today directly accountable to our Fellowship. Its trustees are the caretakers and expediters of our world services.</p>

<p>Just as the aim of each A.A. member is personal sobriety, the aim of our services is to bring sobriety within reach of all who want it. If nobody does the group's chores, if the area's telephone rings unanswered, if we do not reply to our mail, then A.A. as we know it would stop. Our communications lines with those who need our help would be broken.</p>

<p><span class="highlight-result">A.A. has to function, but at the same time it must avoid those dangers of great wealth, prestige, and entrenched power which necessarily tempt other societies. Though Tradition Nine at first sight seems to deal with a purely practical matter, in its actual operation it discloses a society without organization, animated only by the spirit of service—a true fellowship.</span></p>
</div>
`
};

export default chapterContent10;