export const chapterContent = {
  'contents': `
<h2 class="text-xl font-semibold text-white mb-6">Contents</h2>

<div class="space-y-4 text-slate-300">
<p><strong>Foreword</strong> — 15</p>

<h3 class="text-lg font-semibold text-teal-400 mt-8 mb-4">THE TWELVE STEPS</h3>

<p><strong>Step One</strong> — 21<br/>
<em>"We admitted we were powerless over alcohol—that our lives had become unmanageable."</em><br/>
Who cares to admit complete defeat? Admission of powerlessness is the first step in liberation. Relation of humility to sobriety. Mental obsession plus physical allergy. Why must every A.A. hit bottom?</p>

<p><strong>Step Two</strong> — 25<br/>
<em>"Came to believe that a Power greater than ourselves could restore us to sanity."</em><br/>
What can we believe in? A.A. does not demand belief; Twelve Steps are only suggestions. Importance of an open mind. Variety of ways to faith. Substitution of A.A. as Higher Power. Plight of the disillusioned. Roadblocks of indifference and prejudice. Lost faith found in A.A. Problems of intellectuality and self-sufficiency. Negative and positive thinking. Self-righteousness. Defiance is an outstanding characteristic of alcoholics. Step Two is a rallying point to sanity. Right relation to God.</p>

<p><strong>Step Three</strong> — 34<br/>
<em>"Made a decision to turn our will and our lives over to the care of God, as we understood Him."</em><br/>
Step Three is like opening of a locked door. How shall we let God into our lives? Willingness is the key. Dependence as a means to independence. Dangers of self-sufficiency. Turning our will over to Higher Power. Misuse of willpower. Sustained and personal exertion necessary to conform to God's will.</p>

<p><strong>Step Four</strong> — 42<br/>
<em>"Made a searching and fearless moral inventory of ourselves."</em><br/>
How instincts can exceed their proper function. Step Four is an effort to discover our liabilities. Basic problem of extremes in instinctive drives. Misguided moral inventory can result in guilt, grandiosity, or blaming others. Assets can be noted with liabilities. Self-justification is dangerous. Willingness to take inventory brings light and new confidence. Step Four is beginning of lifetime practice. Common symptoms of emotional insecurity are worry, anger, self-pity, and depression. Inventory reviews relationships. Importance of thoroughness.</p>

<p><strong>Step Five</strong> — 55<br/>
<em>"Admitted to God, to ourselves, and to another human being the exact nature of our wrongs."</em><br/>
Twelve Steps deflate ego. Step Five is difficult but necessary to sobriety and peace of mind. Confession is an ancient discipline. Without fearless admission of defects, few could stay sober. What do we receive from Step Five? Beginning of true kinship with man and God. Lose sense of isolation, receive forgiveness and give it; learn humility; gain honesty and realism about ourselves. Necessity for complete honesty. Danger of rationalization. How to choose the person in whom to confide. Results are tranquility and consciousness of God. Oneness with God and man prepares us for following Steps.</p>

<p><strong>Step Six</strong> — 63<br/>
<em>"Were entirely ready to have God remove all these defects of character."</em><br/>
Step Six necessary to spiritual growth. The beginning of a lifetime job. Recognition of difference between striving for objective—and perfection. Why we must keep trying. "Being ready" is all-important. Necessity of taking action. Delay is dangerous. Rebellion may be fatal. Point at which we abandon limited objectives and move toward God's will for us.</p>

<p><strong>Step Seven</strong> — 70<br/>
<em>"Humbly asked Him to remove our shortcomings."</em><br/>
What is humility? What can it mean to us? The avenue to true freedom of the human spirit. Necessary aid to survival. Value of ego-puncturing. Failure and misery transformed by humility. Strength from weakness. Pain is the admission price to new life. Self-centered fear chief activator of defects. Step Seven is change in attitude which permits us to move out of ourselves toward God.</p>

<p><strong>Step Eight</strong> — 77<br/>
<em>"Made a list of all persons we had harmed, and became willing to make amends to them all."</em><br/>
This and the next two Steps are concerned with personal relations. Learning to live with others is a fascinating adventure. Obstacles: reluctance to forgive; nonadmission of wrongs to others; purposeful forgetting. Necessity of exhaustive survey of past. Deepening insight results from thoroughness. Kinds of harm done to others. Avoiding extreme judgments. Taking the objective view. Step Eight is the beginning of the end of isolation.</p>

<p><strong>Step Nine</strong> — 83<br/>
<em>"Made direct amends to such people wherever possible, except when to do so would injure them or others."</em><br/>
A tranquil mood is the first requisite for good judgment. Good timing is important in making amends. What is courage? Prudence means taking calculated chances. Amends begin when we join A.A. Peace of mind cannot be bought at the expense of others. Need for discretion. Readiness to take consequences of our past and to take responsibility for well-being of others is spirit of Step Nine.</p>

<p><strong>Step Ten</strong> — 88<br/>
<em>"Continued to take personal inventory and when we were wrong promptly admitted it."</em><br/>
Can we stay sober and keep emotional balance under all conditions? Self-searching becomes a regular habit. Admit, accept, and patiently correct defects. Emotional hangover. When past is settled with, present challenges can be met. Varieties of inventory. Anger, resentments, jealousy, envy, self-pity, hurt pride—all led to the bottle. Self-restraint first objective. Insurance against "big-shot-ism." Let's look at credits as well as debits. Examination of motives.</p>

<p><strong>Step Eleven</strong> — 96<br/>
<em>"Sought through prayer and meditation to improve our conscious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out."</em><br/>
Meditation and prayer main channels to Higher Power. Connection between self-examination and meditation and prayer. An unshakable foundation for life. How shall we meditate? Meditation has no boundaries. An individual adventure. First result is emotional balance. What about prayer? Daily petitions for understanding of God's will and grace to carry it out. Actual results of prayer are beyond question. Rewards of meditation and prayer.</p>

<p><strong>Step Twelve</strong> — 106<br/>
<em>"Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs."</em><br/>
Joy of living is the theme of the Twelfth Step. Action its keyword. Giving that asks no reward. Love that has no price tag. What is spiritual awakening? A new state of consciousness and being is received as a free gift. Readiness to receive free gift lies in practice of Twelve Steps. The magnificent reality. Rewards of helping other alcoholics. Kinds of Twelfth Step work. Problems of Twelfth Step work. What about the practice of these principles in all our affairs? Monotony, pain and calamity turned to good use by practice of Steps. Difficulties of practice. "Two-stepping." Switch to "twelve-stepping" and demonstrations of faith. Growing spiritually is the answer to our problems. Placing spiritual growth first. Domination and overdependence. Putting our lives on give-and-take basis. Dependence upon God necessary to recovery of alcoholics. "Practicing these principles in all our affairs": Domestic relations in A.A. Outlook upon material matters changes. So do feelings about personal importance. Instincts restored to true purpose. Understanding is key to right attitudes, right action key to good living.</p>

<h3 class="text-lg font-semibold text-teal-400 mt-8 mb-4">THE TWELVE TRADITIONS</h3>

<p><strong>Tradition One</strong> — 129<br/>
<em>"Our common welfare should come first; personal recovery depends upon A.A. unity."</em><br/>
Without unity, A.A. dies. Individual liberty, yet great unity. Key to paradox: each A.A.'s life depends on obedience to spiritual principles. The group must survive or the individual will not. Common welfare comes first. How best to live and work together as groups.</p>

<p><strong>Tradition Two</strong> — 132<br/>
<em>"For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience. Our leaders are but trusted servants; they do not govern."</em><br/>
Where does A.A. get its direction? Sole authority in A.A. is loving God as He may express Himself in the group conscience. Formation of a group. Growing pains. Rotating committees are servants of the group. Leaders do not govern, they serve. Does A.A. have a real leadership? "Elder statesmen" and "bleeding deacons." The group conscience speaks.</p>

<p><strong>Tradition Three</strong> — 139<br/>
<em>"The only requirement for A.A. membership is a desire to stop drinking."</em><br/>
Early intolerance based on fear. To take away any alcoholic's chance at A.A. was sometimes to pronounce his death sentence. Membership regulations abandoned. Two examples of experience. Any alcoholic is a member of A.A. when he says so.</p>

<p><strong>Tradition Four</strong> — 146<br/>
<em>"Each group should be autonomous except in matters affecting other groups or A.A. as a whole."</em><br/>
Every group manages its affairs as it pleases, except when A.A. as a whole is threatened. Is such liberty dangerous? The group, like the individual, must eventually conform to principles that guarantee survival. Two storm signals—a group ought not do anything which would injure A.A. as a whole, nor affiliate itself with outside interests. An example: the "A.A. Center" that didn't work.</p>

<p><strong>Tradition Five</strong> — 150<br/>
<em>"Each group has but one primary purpose—to carry the message to the alcoholic who still suffers."</em><br/>
Better do one thing well than many badly. The life of our Fellowship depends on this principle. The ability of each A.A. to identify himself with and bring recovery to the newcomer is a gift from God . . . passing on this gift to others is our one aim. Sobriety can't be kept unless it is given away.</p>

<p><strong>Tradition Six</strong> — 155<br/>
<em>"An A.A. group ought never endorse, finance or lend the A.A. name to any related facility or outside enterprise, lest problems of money, property and prestige divert us from our primary purpose."</em><br/>
Experience proved that we could not endorse any related enterprise, no matter how good. We could not be all things to all men. We saw that we could not lend the A.A. name to any outside activity.</p>

<p><strong>Tradition Seven</strong> — 160<br/>
<em>"Every A.A. group ought to be fully self-supporting, declining outside contributions."</em><br/>
No A.A. Tradition had the labor pains this one did. Collective poverty initially a matter of necessity. Fear of exploitation. Necessity of separating the spiritual from the material. Decision to subsist on A.A. voluntary contributions only. Placing the responsibility of supporting A.A. headquarters directly upon A.A. members. Bare running expenses plus a prudent reserve is headquarters policy.</p>

<p><strong>Tradition Eight</strong> — 166<br/>
<em>"Alcoholics Anonymous should remain forever nonprofessional, but our service centers may employ special workers."</em><br/>
You can't mix the Twelfth Step and money. Line of cleavage between voluntary Twelfth Step work and paid-for services. A.A. could not function without full-time service workers. Professional workers are not professional A.A.'s. Relation of A.A. to industry, education, etc. Twelfth Step work is never paid for, but those who labor in service for us are worthy of their hire.</p>

<p><strong>Tradition Nine</strong> — 172<br/>
<em>"A.A., as such, ought never be organized; but we may create service boards or committees directly responsible to those they serve."</em><br/>
Special service boards and committees. The General Service Conference, the board of trustees, and group committees cannot issue directives to A.A. members or groups. A.A.'s can't be dictated to—individually or collectively. Absence of coercion works because unless each A.A. follows suggested Steps to recovery, he signs his own death warrant. Same condition applies to the group. Suffering and love are A.A.'s disciplinarians. Difference between spirit of authority and spirit of service. Aim of our services is to bring sobriety within reach of all who want it.</p>

<p><strong>Tradition Ten</strong> — 176<br/>
<em>"Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy."</em><br/>
A.A. does not take sides in any public controversy. Reluctance to fight is not a special virtue. Survival and spread of A.A. are our primary aims. Lessons learned from Washingtonian movement.</p>

<p><strong>Tradition Eleven</strong> — 180<br/>
<em>"Our public relations policy is based on attraction rather than promotion; we need always maintain personal anonymity at the level of press, radio and films."</em><br/>
Public relations are important to A.A. Good public relations save lives. We seek publicity for A.A. principles, not A.A. members. The press has cooperated. Personal anonymity at the public level is the cornerstone of our public relations policy. Eleventh Tradition is a constant reminder that personal ambition has no place in A.A. Each member becomes an active guardian of our Fellowship.</p>

<p><strong>Tradition Twelve</strong> — 184<br/>
<em>"Anonymity is the spiritual foundation of all our traditions, ever reminding us to place principles before personalities."</em><br/>
Spiritual substance of anonymity is sacrifice. Subordinating personal aims to the common good is the essence of all Twelve Traditions. Why A.A. could not remain a secret society. Principles come before personalities. One hundred percent anonymity at the public level. Anonymity is real humility.</p>

<p><strong>The Twelve Traditions—the Long Form</strong> — 189</p>
</div>
`,

  'foreword': `
<h2 class="text-xl font-semibold text-white mb-6">Foreword</h2>

<div class="prose prose-invert prose-slate max-w-none">
<p>ALCOHOLICS ANONYMOUS is a worldwide fellowship of more than one hundred thousand* alcoholic men and women who are banded together to solve their common problems and to help fellow sufferers in recovery from that age-old, baffling malady, alcoholism.</p>

<p>This book deals with the "Twelve Steps" and the "Twelve Traditions" of Alcoholics Anonymous. It presents an explicit view of the principles by which A.A. members recover and by which their Society functions.</p>

<p>A.A.'s Twelve Steps are a group of principles, spiritual in their nature, which, if practiced as a way of life, can expel the obsession to drink and enable the sufferer to become happily and usefully whole.</p>

<p>A.A.'s Twelve Traditions apply to the life of the Fellowship itself. They outline the means by which A.A. maintains its unity and relates itself to the world about it, the way it lives and grows.</p>

<p>Though the essays which follow were written mainly for members, it is thought by many of A.A.'s friends that these pieces might arouse interest and find application outside of A.A. itself.</p>

<p>Many people, nonalcoholics, report that as a result of the practice of A.A.'s Twelve Steps, they have been able to meet other difficulties of life. They think that the Twelve Steps can mean more than sobriety for problem drinkers. They see in them a way to happy and effective living for many, alcoholic or not.</p>

<p>There is, too, a rising interest in the Twelve Traditions of Alcoholics Anonymous. Students of human relations are beginning to wonder how and why A.A. functions as a society. Why is it, they ask, that in A.A. no member can be set in personal authority over another, that nothing like a central government can anywhere be seen? How can a set of traditional principles, having no legal force at all, hold the Fellowship of Alcoholics Anonymous in unity and effectiveness? The second section of this volume, though designed for A.A.'s membership, will give such inquirers an inside view of A.A. never before possible.</p>

<p>Alcoholics Anonymous began in 1935 in Akron, Ohio, as the outcome of a meeting between a well-known surgeon and a New York broker. Both were severe cases of alcoholism and were destined to become co-founders of the A.A. Fellowship.</p>

<p>The basic principles of A.A., as they are known today, were borrowed mainly from the fields of religion and medicine, though some ideas upon which success finally depended were the result of noting the behavior and needs of the Fellowship itself.</p>

<p>After three years of trial and error in selecting the most workable tenets upon which the Society could be based, and after a large amount of failure in getting alcoholics to recover, three successful groups emerged—the first at Akron, the second in New York, and the third at Cleveland. Even then it was hard to find twoscore of sure recoveries in all three groups.</p>

<p>Nevertheless, the infant Society determined to set down its experience in a book which finally reached the public in April 1939. At this time the recoveries numbered about one hundred. The book was called "Alcoholics Anonymous" and from it the Fellowship took its name. In it alcoholism was described from the alcoholic's view, the spiritual idea of the Society was codified for the first time in the Twelve Steps, and the application of these Steps to the alcoholic's dilemma was made clear. The remainder of the book was devoted to thirty stories or case histories in which the alcoholics described their drinking experiences and recoveries. This established identification with alcoholic readers and proved to them that the virtually impossible had become possible. The book "Alcoholics Anonymous" became the basic text of the Fellowship, and it still is. This present volume proposes to broaden and deepen the understanding of the Twelve Steps as first written in the earlier work.</p>

<p>With the publication of the book "Alcoholics Anonymous" in 1939, the pioneering period ended and a prodigious chain reaction set in as recovered alcoholics carried their message to still others. In the next years alcoholics flocked to A.A. by tens of thousands, largely as the result of excellent and continuous publicity freely given by magazines and newspapers throughout the world. Clergymen and doctors alike rallied to the new movement, giving it unstinted support and endorsement.</p>

<p>This startling expansion brought with it very severe growing pains. Proof that alcoholics could recover had been made. But it was by no means sure that such great numbers of yet erratic people could live and work together with harmony and good effect.</p>

<p>Everywhere there arose threatening questions of membership, money, personal relations, public relations, management of groups, clubs, and scores of other perplexities. It was out of this vast welter of explosive experiences that A.A.'s Twelve Traditions took form and were first published in 1946 and later confirmed at A.A.'s First International Convention held at Cleveland in 1950. The Tradition section of this volume portrays in some detail the experience which finally produced the Twelve Traditions and so gave A.A. its present form, substance, and unity.</p>

<p>As A.A. now enters maturity, it has begun to reach into forty foreign lands.* In the view of its friends, this is but the beginning of its unique and valuable service.</p>

<p>It is hoped that this volume will afford all who read it a close-up view of the principles and forces which have made Alcoholics Anonymous what it is.</p>

<p class="text-sm text-slate-500 mt-8">*In 2003 it is estimated that over two million have recovered through A.A.</p>
<p class="text-sm text-slate-500">*In 2003, A.A. is established in approximately 150 countries.</p>

<p class="text-sm text-slate-400 mt-6">(A.A.'s General Service Office may be reached by writing: Alcoholics Anonymous, P.O. Box 459, Grand Central Station, New York, NY 10163, U.S.A.)</p>
</div>
`,

  'step-one': `
<h2 class="text-xl font-semibold text-white mb-2">Step One</h2>
<p class="text-teal-400 italic mb-6">"We admitted we were powerless over alcohol—that our lives had become unmanageable."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>WHO cares to admit complete defeat? Practically no one, of course. Every natural instinct cries out against the idea of personal powerlessness. It is truly awful to admit that, glass in hand, we have warped our minds into such an obsession for destructive drinking that only an act of providence can remove it from us.</p>

<p><span class="highlight-problem">No other kind of bankruptcy is like this one. Alcohol, now become the rapacious creditor, bleeds us of all self-sufficiency and all will to resist its demands.</span> Once this stark fact is accepted, our bankruptcy as going human concerns is complete.</p>

<p><span class="highlight-solution">But upon entering A.A. we soon take quite another view of this absolute humiliation. We perceive that only through utter defeat are we able to take our first steps toward liberation and strength.</span> Our admissions of personal powerlessness finally turn out to be firm bedrock upon which happy and purposeful lives may be built.</p>

<p>We know that little good can come to any alcoholic who joins A.A. unless he has first accepted his devastating weakness and all its consequences. Until he so humbles himself, his sobriety—if any—will be precarious. Of real happiness he will find none at all. Proved beyond doubt by an immense experience, this is one of the facts of A.A. life. The principle that we shall find no enduring strength until we first admit complete defeat is the main taproot from which our whole Society has sprung and flowered.</p>

<p>When first challenged to admit defeat, most of us revolted. We had approached A.A. expecting to be taught self-confidence. Then we had been told that so far as alcohol is concerned, self-confidence was no good whatever; in fact, it was a total liability. Our sponsors declared that we were the victims of a mental obsession so subtly powerful that no amount of human willpower could break it. There was, they said, no such thing as the personal conquest of this compulsion by the unaided will. <span class="highlight-problem">Relentlessly deepening our dilemma, our sponsors pointed out our increasing sensitivity to alcohol—an allergy, they called it. The tyrant alcohol wielded a double-edged sword over us: first we were smitten by an insane urge that condemned us to go on drinking, and then by an allergy of the body that insured we would ultimately destroy ourselves in the process.</span> Few indeed were those who, so assailed, had ever won through in singlehanded combat. It was a statistical fact that alcoholics almost never recovered on their own resources. And this had been true, apparently, ever since man had first crushed grapes.</p>

<p>In A.A.'s pioneering time, none but the most desperate cases could swallow and digest this unpalatable truth. Even these "last-gaspers" often had difficulty in realizing how hopeless they actually were. But a few did, and when these laid hold of A.A. principles with all the fervor with which the drowning seize life preservers, they almost invariably got well. That is why the first edition of the book "Alcoholics Anonymous," published when our membership was small, dealt with low-bottom cases only. Many less desperate alcoholics tried A.A., but did not succeed because they could not make the admission of hopelessness.</p>

<p><span class="highlight-result">It is a tremendous satisfaction to record that in the following years this changed. Alcoholics who still had their health, their families, their jobs, and even two cars in the garage, began to recognize their alcoholism.</span> As this trend grew, they were joined by young people who were scarcely more than potential alcoholics. They were spared that last ten or fifteen years of literal hell the rest of us had gone through. Since Step One requires an admission that our lives have become unmanageable, how could people such as these take this Step?</p>

<p><span class="highlight-action">It was obviously necessary to raise the bottom the rest of us had hit to the point where it would hit them. By going back in our own drinking histories, we could show that years before we realized it we were out of control, that our drinking even then was no mere habit, that it was indeed the beginning of a fatal progression.</span> To the doubters we could say, "Perhaps you're not an alcoholic after all. Why don't you try some more controlled drinking, bearing in mind meanwhile what we have told you about alcoholism?" This attitude brought immediate and practical results. It was then discovered that when one alcoholic had planted in the mind of another the true nature of his malady, that person could never be the same again. Following every spree, he would say to himself, "Maybe those A.A.'s were right . . ." After a few such experiences, often years before the onset of extreme difficulties, he would return to us convinced. He had hit bottom as truly as any of us. John Barleycorn himself had become our best advocate.</p>

<p>Why all this insistence that every A.A. must hit bottom first? The answer is that few people will sincerely try to practice the A.A. program unless they have hit bottom. For practicing A.A.'s remaining eleven Steps means the adoption of attitudes and actions that almost no alcoholic who is still drinking can dream of taking. Who wishes to be rigorously honest and tolerant? Who wants to confess his faults to another and make restitution for harm done? Who cares anything about a Higher Power, let alone meditation and prayer? Who wants to sacrifice time and energy in trying to carry A.A.'s message to the next sufferer? No, the average alcoholic, self-centered in the extreme, doesn't care for this prospect—unless he has to do these things in order to stay alive himself.</p>

<p><span class="highlight-result">Under the lash of alcoholism, we are driven to A.A., and there we discover the fatal nature of our situation. Then, and only then, do we become as open-minded to conviction and as willing to listen as the dying can be. We stand ready to do anything which will lift the merciless obsession from us.</span></p>
</div>
`,

  'step-two': `
<h2 class="text-xl font-semibold text-white mb-2">Step Two</h2>
<p class="text-teal-400 italic mb-6">"Came to believe that a Power greater than ourselves could restore us to sanity."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p>THE moment they read Step Two, most A.A. newcomers are confronted with a dilemma, sometimes a serious one. How often have we heard them cry out, "Look what you people have done to us! You have convinced us that we are alcoholics and that our lives are unmanageable. Having reduced us to a state of absolute helplessness, you now declare that none but a Higher Power can remove our obsession. <span class="highlight-problem">Some of us won't believe in God, others can't, and still others who do believe that God exists have no faith whatever He will perform this miracle.</span> Yes, you've got us over the barrel, all right—but where do we go from here?"</p>

<p>Let's look first at the case of the one who says he won't believe—the belligerent one. He is in a state of mind which can be described only as savage. His whole philosophy of life, in which he so gloried, is threatened. It's bad enough, he thinks, to admit alcohol has him down for keeps. But now, still smarting from that admission, he is faced with something really impossible. How he does cherish the thought that man, risen so majestically from a single cell in the primordial ooze, is the spearhead of evolution and therefore the only god that his universe knows! Must he renounce all this to save himself?</p>

<p>At this juncture, his A.A. sponsor usually laughs. This, the newcomer thinks, is just about the last straw. This is the beginning of the end. And so it is: the beginning of the end of his old life, and the beginning of his emergence into a new one. His sponsor probably says, <span class="highlight-solution">"Take it easy. The hoop you have to jump through is a lot wider than you think. At least I've found it so. So did a friend of mine who was a one-time vice-president of the American Atheist Society, but he got through with room to spare."</span></p>

<p>"Well," says the newcomer, "I know you're telling me the truth. It's no doubt a fact that A.A. is full of people who once believed as I do. But just how, in these circumstances, does a fellow 'take it easy'? That's what I want to know."</p>

<p>"That," agrees the sponsor, "is a very good question indeed. I think I can tell you exactly how to relax. You won't have to work at it very hard, either. Listen, if you will, to these three statements. <span class="highlight-action">First, Alcoholics Anonymous does not demand that you believe anything. All of its Twelve Steps are but suggestions. Second, to get sober and to stay sober, you don't have to swallow all of Step Two right now. Looking back, I find that I took it piecemeal myself. Third, all you really need is a truly open mind.</span> Just resign from the debating society and quit bothering yourself with such deep questions as whether it was the hen or the egg that came first. Again I say, all you need is the open mind."</p>

<p>The sponsor continues, "Take, for example, my own case. I had a scientific schooling. Naturally I respected, venerated, even worshiped science. As a matter of fact, I still do—all except the worship part. Time after time, my instructors held up to me the basic principle of all scientific progress: search and research, again and again, always with the open mind. When I first looked at A.A., my reaction was just like yours. This A.A. business, I thought, is totally unscientific. This I can't swallow. I simply won't consider such nonsense.</p>

<p><span class="highlight-result">"Then I woke up. I had to admit that A.A. showed results, prodigious results. I saw that my attitude regarding these had been anything but scientific. It wasn't A.A. that had the closed mind, it was me. The minute I stopped arguing, I could begin to see and feel. Right there, Step Two gently and very gradually began to infiltrate my life.</span> I can't say upon what occasion or upon what day I came to believe in a Power greater than myself, but I certainly have that belief now. To acquire it, I had only to stop fighting and practice the rest of A.A.'s program as enthusiastically as I could.</p>

<p>"This is only one man's opinion based on his own experience, of course. I must quickly assure you that A.A.'s tread innumerable paths in their quest for faith. If you don't care for the one I've suggested, you'll be sure to discover one that suits if only you look and listen. <span class="highlight-solution">Many a man like you has begun to solve the problem by the method of substitution. You can, if you wish, make A.A. itself your 'higher power.' Here's a very large group of people who have solved their alcohol problem. In this respect they are certainly a power greater than you, who have not even come close to a solution. Surely you can have faith in them.</span> Even this minimum of faith will be enough. You will find many members who have crossed the threshold just this way. All of them will tell you that, once across, their faith broadened and deepened. Relieved of the alcohol obsession, their lives unaccountably transformed, they came to believe in a Higher Power, and most of them began to talk of God."</p>

<p>Consider next the plight of those who once had faith, but have lost it. There will be those who have drifted into indifference, those filled with self-sufficiency who have cut themselves off, those who have become prejudiced against religion, and those who are downright defiant because God has failed to fulfill their demands. Can A.A. experience tell all these they may still find a faith that works?</p>

<p><span class="highlight-problem">Sometimes A.A. comes harder to those who have lost or rejected faith than to those who never had any faith at all, for they think they have tried faith and found it wanting. They have tried the way of faith and the way of no faith. Since both ways have proved bitterly disappointing, they have concluded there is no place whatever for them to go.</span> The roadblocks of indifference, fancied self-sufficiency, prejudice, and defiance often prove more solid and formidable for these people than any erected by the unconvinced agnostic or even the militant atheist. Religion says the existence of God can be proved; the agnostic says it can't be proved; and the atheist claims proof of the nonexistence of God. Obviously, the dilemma of the wanderer from faith is that of profound confusion. He thinks himself lost to the comfort of any conviction at all. He cannot attain in even a small degree the assurance of the believer, the agnostic, or the atheist. He is the bewildered one.</p>

<p>Any number of A.A.'s can say to the drifter, "Yes, we were diverted from our childhood faith, too. The overconfidence of youth was too much for us. Of course, we were glad that good home and religious training had given us certain values. We were still sure that we ought to be fairly honest, tolerant, and just, that we ought to be ambitious and hardworking. We became convinced that such simple rules of fair play and decency would be enough.</p>

<p>"As material success founded upon no more than these ordinary attributes began to come to us, we felt we were winning at the game of life. This was exhilarating, and it made us happy. Why should we be bothered with theological abstractions and religious duties, or with the state of our souls here or hereafter? The here and now was good enough for us. The will to win would carry us through. But then alcohol began to have its way with us. Finally, when all our score cards read 'zero,' and we saw that one more strike would put us out of the game forever, we had to look for our lost faith. <span class="highlight-result">It was in A.A. that we rediscovered it. And so can you."</span></p>

<p>Now we come to another kind of problem: the intellectually self-sufficient man or woman. To these, many A.A.'s can say, "Yes, we were like you—far too smart for our own good. We loved to have people call us precocious. We used our education to blow ourselves up into prideful balloons, though we were careful to hide this from others. Secretly, we felt we could float above the rest of the folks on our brainpower alone. Scientific progress told us there was nothing man couldn't do. Knowledge was all-powerful. Intellect could conquer nature. Since we were brighter than most folks (so we thought), the spoils of victory would be ours for the thinking. The god of intellect displaced the God of our fathers. But again John Barleycorn had other ideas. We who had won so handsomely in a walk turned into all-time losers. We saw that we had to reconsider or die. We found many in A.A. who once thought as we did. <span class="highlight-action">They helped us to get down to our right size. By their example they showed us that humility and intellect could be compatible, provided we placed humility first.</span> When we began to do that, we received the gift of faith, a faith which works. This faith is for you, too."</p>

<p>Another crowd of A.A.'s says: "We were plumb disgusted with religion and all its works. The Bible, we said, was full of nonsense; we could cite it chapter and verse, and we couldn't see the Beatitudes for the 'begats.' In spots its morality was impossibly good; in others it seemed impossibly bad. But it was the morality of the religionists themselves that really got us down. We gloated over the hypocrisy, bigotry, and crushing self-righteousness that clung to so many 'believers' even in their Sunday best. How we loved to shout the damaging fact that millions of the 'good men of religion' were still killing one another off in the name of God. This all meant, of course, that we had substituted negative for positive thinking. After we came to A.A., we had to recognize that this trait had been an ego-feeding proposition. In belaboring the sins of some religious people, we could feel superior to all of them. Moreover, we could avoid looking at some of our own shortcomings. <span class="highlight-problem">Self-righteousness, the very thing that we had contemptuously condemned in others, was our own besetting evil. This phony form of respectability was our undoing, so far as faith was concerned.</span> But finally, driven to A.A., we learned better.</p>

<p><span class="highlight-problem">"As psychiatrists have often observed, defiance is the outstanding characteristic of many an alcoholic.</span> So it's not strange that lots of us have had our day at defying God Himself. Sometimes it's because God has not delivered us the good things of life which we specified, as a greedy child makes an impossible list for Santa Claus. More often, though, we had met up with some major calamity, and to our way of thinking lost out because God deserted us. The girl we wanted to marry had other notions; we prayed God that she'd change her mind, but she didn't. We prayed for healthy children, and were presented with sick ones, or none at all. We prayed for promotions at business, and none came. Loved ones, upon whom we heartily depended, were taken from us by so-called acts of God. Then we became drunkards, and asked God to stop that. But nothing happened. This was the unkindest cut of all. 'Damn this faith business!' we said.</p>

<p>"When we encountered A.A., the fallacy of our defiance was revealed. At no time had we asked what God's will was for us; instead we had been telling Him what it ought to be. No man, we saw, could believe in God and defy Him, too. <span class="highlight-solution">Belief meant reliance, not defiance. In A.A. we saw the fruits of this belief: men and women spared from alcohol's final catastrophe. We saw them meet and transcend their other pains and trials. We saw them calmly accept impossible situations, seeking neither to run nor to recriminate. This was not only faith; it was faith that worked under all conditions.</span> We soon concluded that whatever price in humility we must pay, we would pay."</p>

<p>Now let's take the guy full of faith, but still reeking of alcohol. He believes he is devout. His religious observance is scrupulous. He's sure he still believes in God, but suspects that God doesn't believe in him. He takes pledges and more pledges. Following each, he not only drinks again, but acts worse than the last time. Valiantly he tries to fight alcohol, imploring God's help, but the help doesn't come. What, then, can be the matter?</p>

<p>To clergymen, doctors, friends, and families, the alcoholic who means well and tries hard is a heartbreaking riddle. To most A.A.'s, he is not. There are too many of us who have been just like him, and have found the riddle's answer. <span class="highlight-problem">This answer has to do with the quality of faith rather than its quantity. This has been our blind spot. We supposed we had humility when really we hadn't. We supposed we had been serious about religious practices when, upon honest appraisal, we found we had been only superficial. Or, going to the other extreme, we had wallowed in emotionalism and had mistaken it for true religious feeling. In both cases, we had been asking something for nothing. The fact was we really hadn't cleaned house so that the grace of God could enter us and expel the obsession.</span> In no deep or meaningful sense had we ever taken stock of ourselves, made amends to those we had harmed, or freely given to any other human being without any demand for reward. We had not even prayed rightly. We had always said, "Grant me my wishes" instead of "Thy will be done." The love of God and man we understood not at all. Therefore we remained self-deceived, and so incapable of receiving enough grace to restore us to sanity.</p>

<p>Few indeed are the practicing alcoholics who have any idea how irrational they are, or seeing their irrationality, can bear to face it. Some will be willing to term themselves "problem drinkers," but cannot endure the suggestion that they are in fact mentally ill. They are abetted in this blindness by a world which does not understand the difference between sane drinking and alcoholism. "Sanity" is defined as "soundness of mind." Yet no alcoholic, soberly analyzing his destructive behavior, whether the destruction fell on the dining-room furniture or his own moral fiber, can claim "soundness of mind" for himself.</p>

<p><span class="highlight-result">Therefore, Step Two is the rallying point for all of us. Whether agnostic, atheist, or former believer, we can stand together on this Step. True humility and an open mind can lead us to faith, and every A.A. meeting is an assurance that God will restore us to sanity if we rightly relate ourselves to Him.</span></p>
</div>
`,

  'step-three': `
<h2 class="text-xl font-semibold text-white mb-2">Step Three</h2>
<p class="text-teal-400 italic mb-6">"Made a decision to turn our will and our lives over to the care of God, as we understood Him."</p>

<div class="prose prose-invert prose-slate max-w-none">
<p><span class="highlight-action">PRACTICING Step Three is like the opening of a door which to all appearances is still closed and locked. All we need is a key, and the decision to swing the door open. There is only one key, and it is called willingness.</span> Once unlocked by willingness, the door opens almost of itself, and looking through it, we shall see a pathway beside which is an inscription. It reads: "This is the way to a faith that works." In the first two Steps we were engaged in reflection. We saw that we were powerless over alcohol, but we also perceived that faith of some kind, if only in A.A. itself, is possible to anyone. These conclusions did not require action; they required only acceptance.</p>

<p>Like all the remaining Steps, Step Three calls for affirmative action, for it is only by action that we can cut away the self-will which has always blocked the entry of God—or, if you like, a Higher Power—into our lives. Faith, to be sure, is necessary, but faith alone can avail nothing. We can have faith, yet keep God out of our lives. Therefore our problem now becomes just how and by what specific means shall we be able to let Him in? Step Three represents our first attempt to do this. In fact, the effectiveness of the whole A.A. program will rest upon how well and earnestly we have tried to come to "a decision to turn our will and our lives over to the care of God as we understood Him."</p>

<p>To every worldly and practical-minded beginner, this Step looks hard, even impossible. No matter how much one wishes to try, exactly how can he turn his own will and his own life over to the care of whatever God he thinks there is? Fortunately, we who have tried it, and with equal misgivings, can testify that anyone, anyone at all, can begin to do it. We can further add that a beginning, even the smallest, is all that is needed. <span class="highlight-solution">Once we have placed the key of willingness in the lock and have the door ever so slightly open, we find that we can always open it some more. Though self-will may slam it shut again, as it frequently does, it will always respond the moment we again pick up the key of willingness.</span></p>

<p>Maybe this all sounds mysterious and remote, something like Einstein's theory of relativity or a proposition in nuclear physics. It isn't at all. Let's look at how practical it actually is. Every man and woman who has joined A.A. and intends to stick has, without realizing it, made a beginning on Step Three. Isn't it true that in all matters touching upon alcohol, each of them has decided to turn his or her life over to the care, protection, and guidance of Alcoholics Anonymous? Already a willingness has been achieved to cast out one's own will and one's own ideas about the alcohol problem in favor of those suggested by A.A. Any willing newcomer feels sure A.A. is the only safe harbor for the foundering vessel he has become. Now if this is not turning one's will and life over to a newfound Providence, then what is it?</p>

<p>But suppose that instinct still cries out, as it certainly will, "Yes, respecting alcohol, I guess I have to be dependent upon A.A., but in all other matters I must still maintain my independence. Nothing is going to turn me into a nonentity. If I keep on turning my life and my will over to the care of Something or Somebody else, what will become of me? I'll look like the hole in the doughnut." This, of course, is the process by which instinct and logic always seek to bolster egotism, and so frustrate spiritual development. The trouble is that this kind of thinking takes no real account of the facts. And the facts seem to be these: <span class="highlight-result">The more we become willing to depend upon a Higher Power, the more independent we actually are. Therefore dependence, as A.A. practices it, is really a means of gaining true independence of the spirit.</span></p>

<p>Let's examine for a moment this idea of dependence at the level of everyday living. In this area it is startling to discover how dependent we really are, and how unconscious of that dependence. Every modern house has electric wiring carrying power and light to its interior. We are delighted with this dependence; our main hope is that nothing will ever cut off the supply of current. By so accepting our dependence upon this marvel of science, we find ourselves more independent personally. Not only are we more independent, we are even more comfortable and secure. Power flows just where it is needed. Silently and surely, electricity, that strange energy so few people understand, meets our simplest daily needs, and our most desperate ones, too. Ask the polio sufferer confined to an iron lung who depends with complete trust upon a motor to keep the breath of life in him.</p>

<p><span class="highlight-problem">But the moment our mental or emotional independence is in question, how differently we behave. How persistently we claim the right to decide all by ourselves just what we shall think and just how we shall act.</span> Oh yes, we'll weigh the pros and cons of every problem. We'll listen politely to those who would advise us, but all the decisions are to be ours alone. Nobody is going to meddle with our personal independence in such matters. Besides, we think, there is no one we can surely trust. We are certain that our intelligence, backed by willpower, can rightly control our inner lives and guarantee us success in the world we live in. This brave philosophy, wherein each man plays God, sounds good in the speaking, but it still has to meet the acid test: how well does it actually work? One good look in the mirror ought to be answer enough for any alcoholic.</p>

<p>Should his own image in the mirror be too awful to contemplate (and it usually is), he might first take a look at the results normal people are getting from self-sufficiency. Everywhere he sees people filled with anger and fear, society breaking up into warring fragments. Each fragment says to the others, "We are right and you are wrong." Every such pressure group, if it is strong enough, self-righteously imposes its will upon the rest. And everywhere the same thing is being done on an individual basis. The sum of all this mighty effort is less peace and less brotherhood than before. <span class="highlight-problem">The philosophy of self-sufficiency is not paying off. Plainly enough, it is a bone-crushing juggernaut whose final achievement is ruin.</span></p>

<p>Therefore, we who are alcoholics can consider ourselves fortunate indeed. Each of us has had his own near-fatal encounter with the juggernaut of self-will, and has suffered enough under its weight to be willing to look for something better. So it is by circumstance rather than by any virtue that we have been driven to A.A., have admitted defeat, have acquired the rudiments of faith, and now want to make a decision to turn our will and our lives over to a Higher Power.</p>

<p>We realize that the word "dependence" is as distasteful to many psychiatrists and psychologists as it is to alcoholics. Like our professional friends, we, too, are aware that there are wrong forms of dependence. We have experienced many of them. No adult man or woman, for example, should be in too much emotional dependence upon a parent. They should have been weaned long before, and if they have not been, they should wake up to the fact. This very form of faulty dependence has caused many a rebellious alcoholic to conclude that dependence of any sort must be intolerably damaging. <span class="highlight-result">But dependence upon an A.A. group or upon a Higher Power hasn't produced any baleful results.</span></p>

<p>When World War II broke out, this spiritual principle had its first major test. A.A.'s entered the services and were scattered all over the world. Would they be able to take discipline, stand up under fire, and endure the monotony and misery of war? Would the kind of dependence they had learned in A.A. carry them through? Well, it did. They had even fewer alcoholic lapses or emotional binges than A.A.'s safe at home did. They were just as capable of endurance and valor as any other soldiers. Whether in Alaska or on the Salerno beachhead, their dependence upon a Higher Power worked. And far from being a weakness, this dependence was their chief source of strength.</p>

<p>So how, exactly, can the willing person continue to turn his will and his life over to the Higher Power? He made a beginning, we have seen, when he commenced to rely upon A.A. for the solution of his alcohol problem. By now, though, the chances are that he has become convinced that he has more problems than alcohol, and that some of these refuse to be solved by all the sheer personal determination and courage he can muster. They simply will not budge; they make him desperately unhappy and threaten his newfound sobriety. Our friend is still victimized by remorse and guilt when he thinks of yesterday. Bitterness still overpowers him when he broods upon those he still envies or hates. His financial insecurity worries him sick, and panic takes over when he thinks of all the bridges to safety that alcohol burned behind him. And how shall he ever straighten out that awful jam that cost him the affection of his family and separated him from them? His lone courage and unaided will cannot do it. Surely he must now depend upon Somebody or Something else.</p>

<p>At first that "somebody" is likely to be his closest A.A. friend. He relies upon the assurance that his many troubles, now made more acute because he cannot use alcohol to kill the pain, can be solved, too. Of course the sponsor points out that our friend's life is still unmanageable even though he is sober, that after all, only a bare start on A.A.'s program has been made. More sobriety brought about by the admission of alcoholism and by attendance at a few meetings is very good indeed, but it is bound to be a far cry from permanent sobriety and a contented, useful life. That is just where the remaining Steps of the A.A. program come in. <span class="highlight-action">Nothing short of continuous action upon these as a way of life can bring the much-desired result.</span></p>

<p>Then it is explained that other Steps of the A.A. program can be practiced with success only when Step Three is given a determined and persistent trial. This statement may surprise newcomers who have experienced nothing but constant deflation and a growing conviction that human will is of no value whatever. They have become persuaded, and rightly so, that many problems besides alcohol will not yield to a headlong assault powered by the individual alone. But now it appears that there are certain things which only the individual can do. All by himself, and in the light of his own circumstances, he needs to develop the quality of willingness. When he acquires willingness, he is the only one who can make the decision to exert himself. Trying to do this is an act of his own will. All of the Twelve Steps require sustained and personal exertion to conform to their principles and so, we trust, to God's will.</p>

<p><span class="highlight-solution">It is when we try to make our will conform with God's that we begin to use it rightly. To all of us, this was a most wonderful revelation. Our whole trouble had been the misuse of willpower. We had tried to bombard our problems with it instead of attempting to bring it into agreement with God's intention for us.</span> To make this increasingly possible is the purpose of A.A.'s Twelve Steps, and Step Three opens the door.</p>

<p>Once we have come into agreement with these ideas, it is really easy to begin the practice of Step Three. <span class="highlight-action">In all times of emotional disturbance or indecision, we can pause, ask for quiet, and in the stillness simply say: "God grant me the serenity to accept the things I cannot change, courage to change the things I can, and wisdom to know the difference. Thy will, not mine, be done."</span></p>
</div>
`
};

export default chapterContent;